<template><main class="page"><header><div><p class="eyebrow">ADMIN CONSOLE</p><h1>AI 漫剧后台管理</h1></div><el-button @click="$router.push('/')">返回创作台</el-button></header>
<el-tabs v-model="tab" @tab-change="load"><el-tab-pane label="用户与余额" name="users"><div class="toolbar"><el-button type="primary" @click="showCreate=true">新建账号</el-button></div><el-table :data="users"><el-table-column prop="username" label="用户名"/><el-table-column prop="display_name" label="显示名"/><el-table-column prop="role" label="角色"/><el-table-column prop="balance" label="余额"/><el-table-column prop="frozen" label="冻结"/><el-table-column prop="total_granted" label="累计发放"/><el-table-column prop="total_consumed" label="累计消费"/><el-table-column prop="total_refunded" label="累计退款"/><el-table-column label="操作" width="160"><template #default="{row}"><el-button size="small" @click="openBalance(row)">调整积分</el-button></template></el-table-column></el-table></el-tab-pane>
<el-tab-pane label="价目表" name="prices"><div class="toolbar"><el-button type="primary" @click="openPrice()">新建价目表</el-button><span class="unit-tip">金额精确到 0.0001 积分（100 积分 = ¥1）；条件价展示区间，实际按规格匹配。</span></div><el-collapse><el-collapse-item v-for="book in books" :key="book.id" :title="`${book.name} · ${book.status}`"><el-button size="small" @click="openPrice(book)">编辑价目</el-button><el-table :data="book.items" size="small"><el-table-column prop="service_type" label="服务"/><el-table-column prop="model" label="计费键 / 模型"/><el-table-column prop="meter" label="计量方式"/><el-table-column label="单价"><template #default="{row}">{{displayPrice(row)}}</template></el-table-column><el-table-column label="条件"><template #default="{row}">{{rateConditions(row)}}</template></el-table-column><el-table-column label="免费"><template #default="{row}">{{row.is_free?'是':'否'}}</template></el-table-column></el-table></el-collapse-item></el-collapse></el-tab-pane>
<el-tab-pane label="资金流水" name="transactions"><p class="muted">冻结代表预留上限；已结算才是实际扣费，已释放不会扣除积分。</p><BillingTransactionTable :rows="transactions" show-user :total="pages.transactions.total" :page="pages.transactions.page" :page-size="pages.transactions.page_size" @page-change="changePage('transactions',$event)" /></el-tab-pane>
<el-tab-pane label="模型用量" name="usage"><el-table :data="usage" size="small"><el-table-column label="时间" min-width="170"><template #default="{row}">{{formatChinaDateTime(row.created_at)}}</template></el-table-column><el-table-column prop="username" label="用户"/><el-table-column prop="service_type" label="服务"/><el-table-column prop="model" label="模型"/><el-table-column prop="charged" label="积分"/></el-table><LogPagination :meta="pages.usage" @change="changePage('usage',$event)" /></el-tab-pane>
<el-tab-pane label="审计" name="audit"><el-table :data="audits" size="small"><el-table-column label="时间" min-width="170"><template #default="{row}">{{formatChinaDateTime(row.created_at)}}</template></el-table-column><el-table-column prop="actor_username" label="操作者"/><el-table-column prop="action" label="操作"/><el-table-column prop="target_type" label="对象"/></el-table><LogPagination :meta="pages.audit" @change="changePage('audit',$event)" /></el-tab-pane></el-tabs>
<el-dialog v-model="showCreate" title="新建账号" width="420"><el-form :model="newUser" label-position="top"><el-form-item label="用户名"><el-input v-model="newUser.username"/></el-form-item><el-form-item label="显示名"><el-input v-model="newUser.display_name"/></el-form-item><el-form-item label="初始密码"><el-input v-model="newUser.password"/></el-form-item><el-form-item label="角色"><el-select v-model="newUser.role"><el-option value="user" label="普通用户"/><el-option value="admin" label="管理员"/></el-select></el-form-item></el-form><template #footer><el-button type="primary" @click="createUser">创建</el-button></template></el-dialog>
<el-dialog v-model="showBalance" title="调整积分" width="460"><p>{{selected?.username}} · 当前余额 {{selected?.balance ?? 0}} 积分 · 100 积分 = ¥1</p><el-radio-group v-model="balance.mode"><el-radio-button label="adjust">发放／扣减</el-radio-button><el-radio-button label="correct">余额校正</el-radio-button></el-radio-group><el-form label-position="top" style="margin-top:14px"><el-form-item v-if="balance.mode==='adjust'" label="变动积分（正数发放，负数扣减）"><el-input-number v-model="balance.amount_credits" :precision="4" :step="1"/><small class="balance-preview">调整后余额：{{adjustedBalance}}</small></el-form-item><el-form-item v-else label="目标余额（仅用于迁移、对账或历史修正）"><el-input-number v-model="balance.target_credits" :precision="4" :min="0" :step="1"/><small class="balance-preview">将写入差额：{{correctionDelta}}</small></el-form-item><el-form-item label="情况说明（选填）"><el-input v-model="balance.reason" placeholder="可填写发放、扣减或校正原因"/></el-form-item></el-form><template #footer><el-button type="primary" @click="adjust">{{balance.mode==='adjust'?'确认变动':'确认校正'}}</el-button></template></el-dialog>
<el-dialog v-model="showPrice" :title="editingPriceId?'编辑全局价目表':'新建全局价目表'" width="920"><el-form :model="price" label-position="top"><el-form-item label="名称"><el-input v-model="price.name"/></el-form-item><el-form-item label="状态"><el-select v-model="price.status"><el-option value="draft" label="草稿"/><el-option value="published" label="发布"/></el-select></el-form-item><el-form-item label="价格项（单价使用积分，可精确到 0.0001；计量基数在条件中维护）"><el-table :data="price.items" size="small"><el-table-column label="服务" width="130"><template #default="{row}"><el-input v-model="row.service_type" placeholder="video"/></template></el-table-column><el-table-column label="计费键 / 模型" min-width="200"><template #default="{row}"><el-input v-model="row.model"/></template></el-table-column><el-table-column label="计量方式" width="150"><template #default="{row}"><el-select v-model="row.meter"><el-option v-for="m in meters" :key="m" :value="m" :label="m"/></el-select></template></el-table-column><el-table-column label="单价（积分）" width="150"><template #default="{row}"><el-input-number v-model="row.unit_price" :precision="4" :step="0.0001" :min="0"/></template></el-table-column><el-table-column label="免费" width="80"><template #default="{row}"><el-switch v-model="row.is_free"/></template></el-table-column><el-table-column width="70"><template #default="{ $index }"><el-button text type="danger" @click="price.items.splice($index,1)">删除</el-button></template></el-table-column></el-table><el-button style="margin-top:12px" @click="addPriceItem">新增价格项</el-button></el-form-item></el-form><template #footer><el-button type="primary" @click="savePrice">保存</el-button></template></el-dialog>
</main></template>
<script setup>
import { ref, reactive, computed, onMounted, h } from 'vue'; import { ElMessage, ElPagination } from 'element-plus'; import { adminAPI } from '@/api/account'; import BillingTransactionTable from '@/components/BillingTransactionTable.vue'; import { formatChinaDateTime } from '@/utils/time'; import { createClientRequestId } from '@/utils/requestId'
const tab=ref('users'),users=ref([]),books=ref([]),transactions=ref([]),usage=ref([]),audits=ref([]),showCreate=ref(false),showBalance=ref(false),showPrice=ref(false),selected=ref(null),editingPriceId=ref(null),meters=['request','image','second','millisecond','character','input_token','output_token']
const pages=reactive({transactions:{page:1,page_size:20,total:0},usage:{page:1,page_size:20,total:0},audit:{page:1,page_size:20,total:0}})
const LogPagination=(props,{emit})=>props.meta.total>props.meta.page_size?h(ElPagination,{class:'log-pagination',background:true,layout:'prev, pager, next, total',currentPage:props.meta.page,pageSize:props.meta.page_size,total:props.meta.total,onCurrentChange:(page)=>emit('change',page)}):null
LogPagination.props={meta:{type:Object,required:true}};LogPagination.emits=['change']
const newUser=reactive({username:'',display_name:'',password:'',role:'user'}),balance=reactive({mode:'adjust',amount_credits:0,target_credits:0,reason:''}),price=reactive({name:'',status:'draft',items:[]})
const adjustedBalance=computed(()=>Number(((Number(selected.value?.balance)||0)+(Number(balance.amount_credits)||0)).toFixed(4)))
const correctionDelta=computed(()=>Number(((Number(balance.target_credits)||0)-(Number(selected.value?.balance)||0)).toFixed(4)))
function applyPage(target,result){target.value=result.items||[];Object.assign(pages[tab.value],{page:result.page||1,page_size:result.page_size||20,total:result.total||0})}
async function load(){const loaders={users:async()=>users.value=await adminAPI.users(),prices:async()=>books.value=await adminAPI.priceBooks(),transactions:async()=>applyPage(transactions,await adminAPI.transactions(pages.transactions)),usage:async()=>applyPage(usage,await adminAPI.usage(pages.usage)),audit:async()=>applyPage(audits,await adminAPI.audit(pages.audit))};await loaders[tab.value]?.()}
async function changePage(name,page){pages[name].page=page;if(tab.value===name)await load()}
function conditions(row){return row.conditions_json&&typeof row.conditions_json==='object'?row.conditions_json:{}}
function unitSize(row){return Number(conditions(row).unit_size)||1}
function displayPrice(row){const c=conditions(row);const rates=Array.isArray(c.rates)?c.rates:[];if(rates.length){const values=rates.map(r=>Number(r.unit_price_points)).filter(Number.isFinite);if(values.length){const min=Math.min(...values),max=Math.max(...values),value=min===max?String(min):`${min}–${max}`;return `${value} 积分 / ${unitSize(row).toLocaleString()} ${row.meter}（按条件）`}}return `${row.unit_price} 积分 / ${unitSize(row).toLocaleString()} ${row.meter}`}
function rateConditions(row){const c=conditions(row);const tiers=Array.isArray(c.usage_tiers)?c.usage_tiers:[];if(tiers.length)return tiers.map(t=>`${t.selector_meter} ${t.min_inclusive ?? 0}–${t.max_inclusive ?? '∞'}`).join('；');const rates=Array.isArray(c.rates)?c.rates:[];return rates.length?rates.map(r=>r.id||'条件价').join('；'):'基础价'}
async function createUser(){await adminAPI.createUser(newUser);showCreate.value=false;Object.assign(newUser,{username:'',display_name:'',password:'',role:'user'});await load();ElMessage.success('账号已创建')}
function openBalance(row){selected.value=row;Object.assign(balance,{mode:'adjust',amount_credits:0,target_credits:row.balance||0,reason:''});showBalance.value=true} async function adjust(){const idempotency_key=createClientRequestId();if(balance.mode==='adjust'){if(!Number(balance.amount_credits))return ElMessage.warning('变动积分不能为 0');await adminAPI.adjustBalance(selected.value.id,{amount_credits:balance.amount_credits,operation:Number(balance.amount_credits)>0?'grant':'debit',reason:balance.reason,idempotency_key})}else await adminAPI.correctBalance(selected.value.id,{target_credits:balance.target_credits,reason:balance.reason,idempotency_key});showBalance.value=false;await load();window.dispatchEvent(new Event('lmd:balance-changed'));ElMessage.success(balance.mode==='adjust'?'积分已变动':'余额已校正')}
function addPriceItem(){price.items.push({service_type:'image',model:'',meter:'image',unit_price:0,is_free:false})}
function openPrice(book){editingPriceId.value=book?.id||null;Object.assign(price,book?{name:book.name,status:book.status,items:book.items.map(item=>({...item}))}:{name:'',status:'draft',items:[]});if(!price.items.length)addPriceItem();showPrice.value=true}
async function savePrice(){const payload={name:price.name,status:price.status,items:price.items};if(editingPriceId.value)await adminAPI.updatePriceBook(editingPriceId.value,payload);else await adminAPI.createPriceBook(payload);showPrice.value=false;await load();ElMessage.success('价目表已保存')}
onMounted(load)
</script><style scoped>.page{max-width:1250px;margin:auto;padding:28px 20px}.page header{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.eyebrow{letter-spacing:.15em;color:#818cf8;font-size:12px}.toolbar{margin:0 0 14px}.unit-tip{margin-left:12px;color:#6b7280;font-size:13px}.muted{color:#9ca3af;font-size:13px;line-height:1.6}.log-pagination{justify-content:flex-end;margin-top:16px}.balance-preview{display:block;margin-top:6px;color:var(--text-muted)}</style>
