<template>
  <main class="cost-workspace" :aria-busy="busy">
    <header class="page-heading"><div><p class="eyebrow">瑞池传媒 · 运营核算</p><h1>消耗与成本</h1><p>按每日供应商价格和实际用量估算项目成本。全部时间为北京时间。</p></div><router-link class="button" to="/admin">运营工作台与模型定价</router-link></header>
    <nav class="tabs" aria-label="成本工作区"><button v-for="t in tabs" :key="t.key" :aria-current="tab === t.key ? 'page' : undefined" @click="tab = t.key">{{ t.label }}</button></nav>
    <p v-if="error" ref="errorPanel" tabindex="-1" class="feedback error" role="alert">{{ error }}</p><p v-if="notice" class="feedback" role="status">{{ notice }}</p>
    <template v-if="tab === 'query'">
      <section class="panel price-status" aria-label="供应商价格状态"><div class="section-heading"><div><h2>每日供应商价格</h2><p v-if="supplierPrices?.latest">最近成功：{{ supplierPrices.latest.day }} · {{ supplierPrices.latest.models }} 个型号<span v-if="supplierPrices.latest.day !== today" class="warning"> · 今日价格尚未获取</span></p><p v-else>尚无供应商价格快照。未计价用量会明确列出。</p></div><button :disabled="busy || priceRefreshing || supplierPrices?.status === 'completed'" @click="syncPrices">{{ priceRefreshing ? '正在获取价格…' : supplierPrices?.status === 'completed' ? '今日价格已获取' : '获取今日价格' }}</button></div><p>每天自动获取，直接用于成本估算。平台积分价目和人工审核不影响这里的价格。</p><p>账单固定费率：插帧 ¥0.60/分钟 · 画质增强 ¥2.50/分钟。按实际处理时长折算，不参与价格同步或审核。</p><p v-if="supplierPrices?.error" class="warning" role="status">{{ supplierPrices.error }}。仍可使用最近成功的价格估算。</p></section>
      <form class="panel filters" @submit.prevent="refresh(true)">
        <label>开始日期<input v-model="filters.date_from" type="date" required></label><label>结束日期<input v-model="filters.date_to" type="date" required></label>
        <label>客户<select v-model="filters.organization_id" @change="filters.customer_kind = ''"><option value="">全部客户与个人</option><option v-for="c in customers" :key="c.id" :value="String(c.id)">{{ c.name }} #{{ c.id }}</option></select></label>
        <label>项目 ID<input v-model="filters.drama_id" type="number" min="0" placeholder="全部项目"></label><label>执行用户 ID<input v-model="filters.user_id" type="number" min="0" placeholder="全部用户"></label>
        <label>模型<input v-model="filters.model" placeholder="完整模型名"></label><label>操作类型<input v-model="filters.source_kind" placeholder="全部操作"></label>
        <label>计价状态<select v-model="filters.cost_status"><option value="">全部状态</option><option v-for="(label,key) in costStatuses" :key="key" :value="key">{{ label }}</option></select></label>
        <div class="form-actions"><button class="primary" :disabled="busy">查询</button><button type="button" :disabled="busy" @click="reset">重置筛选</button></div><p v-if="filters.customer_kind" class="full">归属：{{ customerLabel(filters.customer_kind) }}</p>
      </form>
      <template v-if="summary">
        <section class="metrics" aria-label="消耗汇总">
          <article><span>供应商成本估算</span><strong>{{ costMoney(summary.supplier_priced_calls ? summary.supplier_amount_micro : null) }}</strong><small>非供应商实付账单；不含未计价部分</small></article>
          <article><span>成本计价覆盖</span><strong>{{ summary.supplier_priced_calls }} / {{ summary.calls - summary.released_calls }}</strong><small>沿用旧价格 {{ summary.supplier_stale_calls }} 条 · 固定费率 {{ summary.supplier_fixed_calls }} 条</small></article>
          <article><span>原平台扣费</span><strong>{{ number(summary.charged_micro / 10000) }} 积分</strong><small>含同笔业务已记录的关联补扣</small></article>
          <article><span>实际 Token</span><strong>{{ number(summary.total_tokens) }}</strong><small>{{ summary.calls }} 条业务记录 · {{ summary.processing_calls }} 条进行中</small></article>
        </section>
        <section class="panel coverage"><p>成本使用调用当日首次成功获取的供应商价格；当日缺失时沿用此前最近价格，并标明日期。历史记录没有更早价格时不套用当前价。原平台扣费独立展示，不用于推算成本。</p><p>已释放且无用量记录 {{ summary.released_calls }} 条 · 缺用量 {{ summary.missing_usage_calls }} 条 · 缺供应商价格或规格 {{ summary.missing_price_calls }} 条 · 待核实 {{ summary.unverified_calls }} 条。</p><p>已结算按结算日期归属，未结算按预授权日期归属。所有汇总使用相同筛选，重试与历史补录不重复累计；未结算记录结算后可能移至另一日期。</p><p>输入 {{ number(summary.input_token) }} · 缓存 {{ number(summary.cache_token) }} · 输出 {{ number(summary.output_token) }} Token（含视频 {{ number(summary.video_output_token) }}）</p><p>图片 {{ number(summary.image) }} 张 · 处理时长 {{ number(summary.millisecond / 1000 + summary.second) }} 秒 · 字符 {{ number(summary.character) }}</p></section>
      </template>
      <section class="panel"><div class="section-heading"><h2>消耗构成</h2><label>分组<select v-model="groupBy" :disabled="busy" @change="groupPage = 1; load()"><option v-for="g in groups" :key="g.key" :value="g.key">{{ g.label }}</option></select></label></div>
        <div class="table-scroll" tabindex="0" aria-label="消耗构成表"><table><thead><tr><th>分组</th><th>业务记录</th><th>供应商成本估算</th><th>原扣费（积分）</th><th>操作</th></tr></thead><tbody><tr v-for="row in breakdown.items" :key="row.key"><td>{{ row.label }}</td><td>{{ row.calls }}</td><td>{{ costMoney(row.supplier_priced_calls ? row.supplier_amount_micro : null) }}<small>{{ row.supplier_priced_calls }} 条已计价</small></td><td>{{ number(row.charged_micro / 10000) }}</td><td><button v-if="['customer','project','user','model','operation'].includes(groupBy)" @click="drill(row)">查看调用</button></td></tr></tbody></table></div><p v-if="!breakdown.total">当前范围内无记录</p>
        <div class="pagination"><button :disabled="busy || groupPage <= 1" @click="groupPage--; load()">上一组页</button><span>第 {{ groupPage }} 页 · {{ breakdown.total }} 组</span><button :disabled="busy || groupPage * 20 >= breakdown.total" @click="groupPage++; load()">下一组页</button></div>
      </section>
      <section class="panel"><h2>调用明细</h2><div class="table-scroll" tabindex="0" aria-label="调用明细表"><table><thead><tr><th>时间 / 状态</th><th>客户 / 项目</th><th>用户 / 模型</th><th>实际用量</th><th>供应商成本估算</th><th>原扣费（积分）</th><th>操作</th></tr></thead><tbody><tr v-for="call in calls.items" :key="call.id"><td>{{ chinaTime(call.occurred_at) }}<small>{{ timeBasis[call.time_basis] }} · {{ statuses[call.status] || call.status }}</small></td><td>{{ call.organization_name || (call.organization_id ? `客户 #${call.organization_id}` : customerLabel(call.customer_kind)) }}<small>{{ call.project_title || '未关联项目' }}</small></td><td>{{ call.user_name }}<small>{{ call.model }}</small></td><td class="usage-cell">{{ usageText(call.usage) }}</td><td>{{ costMoney(call.supplier_amount_micro) }}<small>{{ call.reason }}</small></td><td>{{ call.charged_micro == null ? (call.status === 'released' ? '已释放' : '未结算') : number(call.charged_micro / 10000) }}</td><td><button @click="openCall(call.id)">查看依据</button></td></tr></tbody></table></div><p v-if="!calls.total">当前范围内无记录</p><div class="pagination"><button :disabled="busy || page <= 1" @click="page--; load()">上一页</button><span>第 {{ page }} 页 · {{ calls.total }} 条</span><button :disabled="busy || page * 20 >= calls.total" @click="page++; load()">下一页</button></div></section>
      <section v-if="detail" ref="detailPanel" class="panel" tabindex="-1"><div class="section-heading"><h2>调用依据</h2><button @click="detail = null">关闭详情</button></div><p>{{ detail.project_title }} · {{ detail.model }} · {{ detail.reason }}</p>
        <dl><dt>业务记录</dt><dd>{{ detail.id }}</dd><dt>已有 AI 连接</dt><dd>{{ detail.config_name || '历史记录未保存连接归属' }}<small v-if="detail.config_id">配置 #{{ detail.config_id }} · 共享连接 {{ detail.connection_id || '未使用' }} · {{ detail.provider || '未知供应商' }}</small></dd><dt>供应商请求</dt><dd>{{ detail.provider_request_id || '未保存' }}</dd><dt>价格适用时间</dt><dd>{{ chinaTime(detail.price_at) }}</dd><dt>供应商成本估算</dt><dd>{{ costMoney(detail.supplier_amount_micro) }}（非实付账单）</dd><dt>原扣费 / 关联补扣</dt><dd>{{ detail.original_charged_micro == null ? '未结算' : number(detail.original_charged_micro / 10000) }} / {{ number(detail.supplement_micro / 10000) }} 积分</dd><dt>供应商价格依据</dt><dd>{{ detail.supplier?.source_label || '尚无可用价格' }}<small>{{ detail.supplier?.price_day || '' }}{{ detail.supplier?.stale ? ' · 沿用此前价格' : '' }}</small></dd></dl>
        <h3>供应商价格与实际用量</h3><p v-if="!detail.supplier?.rates?.length">{{ detail.reason }}</p><div v-else class="table-scroll" tabindex="0" aria-label="供应商计费明细"><table><thead><tr><th>计量</th><th>实际 / 计费数量</th><th>供应商单价（元） / 单位数量</th><th>规格</th><th>估算小计（元）</th></tr></thead><tbody><tr v-for="r in detail.supplier.rates" :key="r.meter"><td>{{ meterNames[r.meter] || r.meter }}</td><td>{{ number(r.quantity) }} / {{ number(r.billable_quantity) }}</td><td>{{ number(r.unit_price_cny) }} / {{ r.unit_size }}</td><td>{{ r.rate_id || '标准' }}</td><td>{{ costMoney(r.subtotal_micro) }}</td></tr></tbody></table></div>
        <details><summary>供应商价格快照与调用规格</summary><pre>{{ JSON.stringify({ pricing_context: detail.pricing_context, supplier: detail.supplier, usage_evidence: detail.usage_evidence }, null, 2) }}</pre></details>
        <details><summary>平台积分依据（不用于成本估算）</summary><p>{{ detail.platform_reason }}</p><pre>{{ JSON.stringify(detail.rates, null, 2) }}</pre></details>
        <details v-if="detail.attempts.length"><summary>调用尝试与旧成本修订（不重复计入汇总）</summary><article v-for="a in detail.attempts" :key="a.id" class="revision"><p>{{ a.origin === 'historical_summary' ? '旧历史补录' : `尝试 ${a.attempt}` }} · {{ a.model }} · {{ chinaTime(a.submitted_at) }}</p><p v-for="r in a.revisions" :key="r.id">旧修订 #{{ r.id }}：{{ costMoney(r.amount_micro, r.currency || 'CNY') }} · {{ r.price?.source || '无价格' }} · {{ r.reason }}</p></article></details>
      </section>
    </template>
    <template v-if="tab === 'reports'">
      <section class="panel"><h2>客户月报</h2><p>保存每日供应商价格口径的成本月报，冻结用量、价格日期与估算金额。旧版本保持原值。</p><form class="inline-form" @submit.prevent="saveReport"><label>客户<select v-model="reportForm.organization_id" required><option value="">请选择客户</option><option v-for="c in customers" :key="c.id" :value="c.id">{{ c.name }}</option></select></label><label>自然月<input v-model="reportForm.month" type="month" required></label><button class="primary" :disabled="busy">保存月报新版本</button></form></section>
      <section class="panel"><h2>已保存版本</h2><div class="table-scroll" tabindex="0"><table><thead><tr><th>客户</th><th>月份 / 版本</th><th>保存时间</th><th>操作</th></tr></thead><tbody><tr v-for="r in reports" :key="r.id"><td>{{ customers.find(c => c.id === r.organization_id)?.name || `客户 #${r.organization_id}` }}</td><td>{{ r.month }} · v{{ r.version }}</td><td>{{ chinaTime(r.generated_at) }}</td><td><button @click="showReport(r.id)">查看月报</button></td></tr></tbody></table></div><p v-if="!reports.length">尚无月报</p></section>
      <section v-if="report" class="panel"><h2>{{ report.summary.organization_name }} · {{ report.month }} · v{{ report.version }}</h2><template v-if="report.summary.basis === 'supplier_daily_v1'"><p>每日供应商价格估算 · {{ report.summary.calls }} 条业务记录</p><p>供应商成本估算 {{ costMoney(report.summary.supplier_priced_calls ? report.summary.supplier_amount_micro : null) }} · {{ report.summary.supplier_priced_calls }} 条已计价</p><p>沿用旧价格 {{ report.summary.supplier_stale_calls }} 条 · 固定费率 {{ report.summary.supplier_fixed_calls }} 条 · 缺价格或规格 {{ report.summary.missing_price_calls }} 条</p><p>原平台扣费 {{ number(report.summary.charged_micro / 10000) }} 积分</p></template><template v-else-if="report.summary.basis === 'billing_activity_v1'"><p>旧版平台价目复算（不代表供应商成本） · {{ report.summary.calls }} 条业务记录</p><p>模型计价折合 {{ costMoney(report.summary.calculated_calls ? report.summary.model_amount_micro : null) }} · 供应商费率估算 {{ costMoney(report.summary.supplier_priced_calls ? report.summary.supplier_amount_micro : null) }}（{{ report.summary.supplier_priced_calls }} 条有来源）</p><p>原扣费 {{ number(report.summary.charged_micro / 10000) }} 积分</p></template><p v-else>旧版独立成本规则快照：{{ costMoney(report.summary.cny_micro) }} · {{ report.summary.calls }} 条。此版本保留原值，与当前原调用口径不同。</p><div class="actions"><a class="button" :href="exportUrl(false)">导出汇总 CSV</a><a class="button" :href="exportUrl(true)">导出明细 CSV</a></div></section>
    </template>
  </main>
</template>
<script setup>
import { nextTick, onMounted, onUnmounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { costsAPI as api } from '@/api/costs'
import { adminAPI } from '@/api/account'
import { chinaDate, chinaTime, costMoney, usageText, meterNames } from '@/utils/costPresentation'
const route = useRoute(), router = useRouter(), today = chinaDate()
const tabs = [{ key: 'query', label: '查询与明细' }, { key: 'reports', label: '客户月报' }]
const groups = [{ key: 'project', label: '项目' }, { key: 'customer', label: '客户' }, { key: 'user', label: '用户' }, { key: 'model', label: '模型' }, { key: 'operation', label: '操作' }, { key: 'hour', label: '小时' }, { key: 'day', label: '日期' }, { key: 'month', label: '月份' }]
const statuses = { settled: '已结算', processing: '处理中', released: '已释放', reconciliation: '待对账', completed: '已完成', failed: '失败', unknown: '结果不明' }
const costStatuses = { calculated: '成本已计价', missing_usage: '缺实际用量', missing_price: '缺供应商价格或规格', released: '已释放且无用量', unverified: '待核实' }
const timeBasis = { settlement: '结算时间', authorization: '预授权时间', supplier_submission: '提交时间' }
const defaults = () => ({ date_from: today.slice(0, 7) + '-01', date_to: today, organization_id: '', drama_id: '', user_id: '', model: '', source_kind: '', cost_status: '', customer_kind: '' })
const filters = reactive({ ...defaults(), ...Object.fromEntries(Object.keys(defaults()).filter(k => typeof route.query[k] === 'string').map(k => [k, route.query[k]])) })
const params = () => Object.fromEntries(Object.entries(filters).filter(([, v]) => v !== ''))
const applied = ref(params()), tab = ref('query'), busy = ref(false), error = ref(''), notice = ref(''), errorPanel = ref(null)
const basis = 'supplier_daily_v1', supplierPrices = ref(null), priceRefreshing = ref(false)
let pricePoll = null, disposed = false
const customers = ref([]), reports = ref([]), report = ref(null), summary = ref(null), calls = ref({ items: [], total: 0 }), breakdown = ref({ items: [], total: 0 })
const page = ref(1), groupPage = ref(1), groupBy = ref('project'), detail = ref(null), detailPanel = ref(null)
const reportForm = reactive({ organization_id: '', month: today.slice(0, 7) })
const number = v => Number(v || 0).toLocaleString('zh-CN', { maximumFractionDigits: 4 })
const customerLabel = v => ({ personal: '个人账户', unknown: '未知客户' })[v] || v
async function perform(fn, message = '') { if (busy.value) return; busy.value = true; error.value = ''; notice.value = ''; try { await fn(); notice.value = message } catch (e) { error.value = e.message || '读取失败，请重试' } finally { busy.value = false; if (error.value) { await nextTick(); errorPanel.value?.focus(); errorPanel.value?.scrollIntoView({ block: 'center' }) } } }
async function query() { try { const result = await api.activity({ ...applied.value, basis, page: page.value, group_page: groupPage.value, group_by: groupBy.value }); supplierPrices.value = result.supplier_prices; watchPrices(); summary.value = result.summary; calls.value = result.calls; breakdown.value = result.breakdown } catch (e) { summary.value = null; calls.value = { items: [], total: 0 }; breakdown.value = { items: [], total: 0 }; throw e } }
function load() { return perform(query) }
function refresh(resetPage = false) { return perform(async () => { if (resetPage) { page.value = 1; groupPage.value = 1; detail.value = null } applied.value = params(); await query(); await router.replace({ query: applied.value }) }) }
function reset() { Object.assign(filters, defaults()); refresh(true) }
function drill(row) { if (busy.value) return; Object.assign(filters, defaults(), applied.value); if (groupBy.value === 'customer') { filters.organization_id = ['personal','unknown'].includes(row.key) ? '0' : row.key; filters.customer_kind = ['personal','unknown'].includes(row.key) ? row.key : ''; groupBy.value = 'project' } else { const key = { project: 'drama_id', user: 'user_id', model: 'model', operation: 'source_kind' }[groupBy.value]; filters[key] = row.key === 'unknown' ? '0' : row.key; if (groupBy.value === 'project') groupBy.value = 'user' } refresh(true) }
function openCall(id) { return perform(async () => { detail.value = await api.activityDetail(id, { basis }); await nextTick(); detailPanel.value?.focus(); detailPanel.value?.scrollIntoView({ block: 'start' }) }) }
function saveReport() { return perform(async () => { report.value = await api.saveReport({ ...reportForm, basis }); reports.value = await api.reports() }, '月报新版本已保存。') }
function showReport(id) { return perform(async () => { report.value = await api.report(id) }) }
function exportUrl(detailRows) { return `/api/v1/admin/costs/reports/${encodeURIComponent(report.value.id)}/export?detail=${detailRows}` }
function watchPrices() { priceRefreshing.value = supplierPrices.value?.status === 'processing'; if (priceRefreshing.value && !pricePoll && !disposed) pricePoll = setTimeout(pollPrices, 2500) }
async function pollPrices() { pricePoll = null; if (disposed) return; try { supplierPrices.value = await api.supplierPrices(); watchPrices(); if (!priceRefreshing.value && !busy.value) await load() } catch (e) { priceRefreshing.value = false; error.value = e.message || '无法读取价格状态，请刷新' } }
function syncPrices() { return perform(async () => { supplierPrices.value = await api.syncSupplierPrices(); watchPrices(); if (!priceRefreshing.value) await query() }) }
onUnmounted(() => { disposed = true; clearTimeout(pricePoll) })
onMounted(() => perform(async () => { const [c, r] = await Promise.all([adminAPI.customerOrganizations(), api.reports()]); customers.value = c; reports.value = r; await query() }))
</script>
<style scoped>
.cost-workspace { width: 100%; min-width: 0; max-width: 1680px; margin: 0 auto; padding: 28px; color: var(--text-primary); }
.page-heading,.section-heading,.actions,.pagination,.tabs { display: flex; align-items: center; justify-content: space-between; gap: 12px; flex-wrap: wrap; }
.page-heading { margin-bottom: 22px; }.eyebrow { font-size: 12px; color: var(--text-secondary); letter-spacing: .1em; }h1 { font-size: 28px; margin: 6px 0; }h2 { font-size: 19px; margin: 0 0 14px; }h3 { font-size: 15px; }p { line-height: 1.65; margin: 8px 0; }small { display: block; color: var(--text-secondary); margin-top: 6px; line-height: 1.5; }
.tabs { justify-content: flex-start; border-bottom: 1px solid var(--border-color); padding-bottom: 12px; margin-bottom: 20px; }.tabs [aria-current],.primary { background: var(--el-color-primary, #365cd6); color: white; border-color: transparent; }
button,.button { border: 1px solid var(--border-color); border-radius: 7px; background: var(--bg-raised); color: inherit; padding: 9px 14px; font: inherit; font-size: 13px; cursor: pointer; text-decoration: none; }button:disabled { opacity: .5; cursor: not-allowed; }button:hover:not(:disabled),.button:hover { border-color: var(--el-color-primary); }button.primary { background: var(--el-color-primary); color: #fff; }button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible,.table-scroll:focus-visible { outline: 2px solid var(--el-color-primary); outline-offset: 3px; }
.panel { min-width: 0; padding: 22px; margin-bottom: 20px; border: 1px solid var(--border-color); background: var(--bg-surface); border-radius: 12px; }.filters { display: grid; grid-template-columns: repeat(auto-fit,minmax(175px,1fr)); gap: 16px; align-items: end; }label { display: flex; flex-direction: column; gap: 7px; font-size: 13px; min-width: 0; }input,select,textarea { box-sizing: border-box; width: 100%; min-width: 0; padding: 9px 10px; border: 1px solid var(--border-color); border-radius: 6px; background: var(--bg-raised); color: inherit; font: inherit; }textarea { resize: vertical; font-family: monospace; }.full { grid-column: 1 / -1; }.form-actions,.inline-form { display: flex; flex-wrap: wrap; gap: 12px; align-items: end; }.inline-form { margin: 18px 0; }.inline-form label { flex: 1 1 200px; max-width: 480px; }.checkbox { flex-direction: row; align-items: center; margin: 16px 0; }.checkbox input { width: 17px; height: 17px; }.source-select { max-width: 520px; margin-top: 16px; }
.metrics { display: grid; grid-template-columns: repeat(4,minmax(0,1fr)); gap: 16px; margin: 20px 0; }.metrics article { border-top: 3px solid var(--el-color-primary); background: var(--bg-surface); padding: 20px; border-radius: 9px; }.metrics strong { display: block; font-size: clamp(20px,2vw,30px); margin: 12px 0; overflow-wrap: anywhere; }.metrics span,.muted { color: var(--text-secondary); }.coverage { border-inline-start: 3px solid var(--el-color-primary); }.warning { color: var(--status-warning, #bd7900); }.feedback { border: 1px solid var(--border-color); border-inline-start: 3px solid var(--el-color-primary); padding: 12px 16px; margin-bottom: 16px; overflow-wrap: anywhere; }.error { border-inline-start-color: var(--status-danger, #e45454); color: var(--status-danger, #e45454); }
.table-scroll { overflow-x: auto; width: 100%; margin-top: 14px; }table { border-collapse: collapse; width: 100%; min-width: 740px; text-align: left; font-size: 13px; }th,td { padding: 13px 12px; border-bottom: 1px solid var(--border-color); vertical-align: top; }th { color: var(--text-secondary); font-weight: 500; background: var(--bg-muted); }td { max-width: 310px; overflow-wrap: anywhere; }.usage-cell { min-width: 180px; max-width: 260px; }.pagination { justify-content: flex-end; margin-top: 18px; font-size: 13px; }.section-heading label { min-width: 130px; }.revision { border-top: 1px solid var(--border-color); padding: 16px 0; }pre { white-space: pre-wrap; overflow-wrap: anywhere; max-width: 100%; padding: 12px; background: var(--bg-muted); border-radius: 6px; font-size: 12px; }summary { cursor: pointer; padding: 8px 0; }dl { display: grid; grid-template-columns: 190px minmax(0,1fr); gap: 12px; font-size: 13px; }dt { color: var(--text-secondary); }dd { margin: 0; overflow-wrap: anywhere; }.actions { justify-content: flex-start; }li { margin: 8px 0; }
@media(max-width:800px) { .cost-workspace { padding: 16px; }.metrics { grid-template-columns: repeat(2,minmax(0,1fr)); }.panel { padding: 16px; }.page-heading { align-items: flex-start; }dl { grid-template-columns: 1fr; gap: 6px; }dd { margin-bottom: 10px; }.pagination { justify-content: space-between; } }
@media(max-width:430px) { .metrics { gap: 10px; }.metrics article { padding: 14px; }.metrics strong { font-size: 21px; }.filters { grid-template-columns: 1fr; }.tabs { gap: 8px; }.tabs button { flex: 1 1 40%; } }
</style>
