const test = require('node:test');
const assert = require('node:assert/strict');
const auth = require('../src/services/authService');
const { modelCatalogFixture } = require('./helpers/modelCatalogFixture');

test('project transfer preserves attribution and updates permissions after restart', async t => {
  const f = await modelCatalogFixture();
  t.after(() => f.close());
  const login = (username) => f.request('POST', '/auth/login', { username, password: 'fixture-password' });
  const owner = await login('catalog-admin');
  const editorUser = auth.createUser(f.db, { username: 'next-owner', password: 'fixture-password' });
  const viewerUser = auth.createUser(f.db, { username: 'view-only', password: 'fixture-password' });
  const stranger = auth.createUser(f.db, { username: 'outside', password: 'fixture-password' });
  const editor = await login('next-owner'); const viewer = await login('view-only');
  const request = (actor, method, route, body) => f.request(method, route, body, actor.cookie);
  const created = await request(owner, 'POST', '/dramas', { title: '转让验收' });
  const id = created.body.data.id; const prefix = `/dramas/${id}`;
  for (const [username, role] of [['next-owner', 'editor'], ['view-only', 'viewer']]) assert.equal((await request(owner, 'PUT', `${prefix}/collaboration/members`, { username, role })).status, 200);
  const episode = Number(f.db.prepare('INSERT INTO episodes(drama_id,episode_number,title) VALUES (?,1,?)').run(id, '分集标题').lastInsertRowid);
  const shot = Number(f.db.prepare('INSERT INTO storyboards(episode_id,storyboard_number,title) VALUES (?,1,?)').run(episode, '真实分镜名称').lastInsertRowid);
  const generation = Number(f.db.prepare("INSERT INTO video_generations(drama_id,storyboard_id,owner_user_id,status,local_path) VALUES (?,?,?,'processing',?)").run(id, shot, f.admin.id, 'durable.mp4').lastInsertRowid);
  const before = f.db.prepare('SELECT * FROM video_generations WHERE id=?').get(generation);
  const character = Number(f.db.prepare('INSERT INTO characters(drama_id,name,local_path,image_url) VALUES (?,?,?,?)').run(id, '项目角色', 'resource.png', '/static/resource.png').lastInsertRowid);
  const asset = require('../src/services/assetMappingService').syncEntities(f.db, f.log, 'character', [character])[0];
  const results = (await request(viewer, 'GET', `${prefix}/collaboration/results`)).body.data;
  assert.equal(results[0].storyboard_title, '真实分镜名称');
  assert.equal(results[0].storyboard_number, 1);
  assert.equal(results[0].episode_id, episode);
  assert.equal((await request(editor, 'POST', `${prefix}/collaboration/transfer`, { user_id: viewerUser.id })).status, 403);
  assert.equal((await request(viewer, 'POST', `${prefix}/collaboration/transfer`, { user_id: editorUser.id })).status, 403);
  assert.equal((await request(owner, 'POST', `${prefix}/collaboration/transfer`, { user_id: stranger.id })).status, 400);
  assert.equal((await request(owner, 'POST', `${prefix}/collaboration/transfer`, { user_id: f.admin.id })).status, 400);
  const moved = await request(owner, 'POST', `${prefix}/collaboration/transfer`, { user_id: editorUser.id });
  assert.equal(moved.status, 200);
  assert.equal(moved.body.data.permissions.role, 'editor');
  assert.equal(moved.body.data.members.filter(member => member.role === 'owner').length, 1);
  assert.deepEqual(f.db.prepare('SELECT * FROM video_generations WHERE id=?').get(generation), before);
  await f.restart();
  assert.equal((await request(editor, 'GET', prefix)).body.data.permissions.can_manage, true);
  assert.equal((await request(editor, 'GET', `/assets/${asset.id}`)).status, 200);
  assert.equal(f.db.prepare('SELECT owner_user_id FROM asset_resource_links WHERE asset_id=?').get(asset.id).owner_user_id, editorUser.id);
  assert.equal((await request(owner, 'GET', prefix)).body.data.permissions.can_manage, false);
  assert.equal((await request(owner, 'DELETE', prefix)).status, 403);
  assert.equal((await request(owner, 'PUT', prefix, { title: '原负责人仍可编辑' })).status, 200);
  assert.equal((await request(editor, 'DELETE', prefix)).status, 409, 'active video tasks still prevent project deletion');
  assert.deepEqual(f.db.prepare('SELECT * FROM video_generations WHERE id=?').get(generation), before);
  assert.equal((await request(viewer, 'GET', `${prefix}/collaboration/results`)).body.data[0].storyboard_title, '真实分镜名称');
  f.db.prepare("UPDATE video_generations SET status='completed' WHERE id=?").run(generation);
  assert.equal((await request(editor, 'DELETE', prefix)).status, 200);
  assert.equal((await request(owner, 'GET', prefix)).status, 404);
  assert.equal((await request(viewer, 'GET', prefix)).status, 404);
  assert.equal(f.db.prepare('SELECT local_path FROM video_generations WHERE id=?').get(generation).local_path, 'durable.mp4');
});
