const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const crypto = require('node:crypto');
const { once } = require('node:events');
const Database = require('better-sqlite3');
const express = require('express');
const Y = require('yjs');
const WebSocket = require('ws');
const { runMigrationsAndEnsure } = require('../src/db/migrate');
const auth = require('../src/services/authService');
const { setupRouter } = require('../src/routes');
const { attach } = require('../src/services/projectCollaborationSocket');

test('project HTTP permissions, concurrent text, copies and restart persistence', async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'project-collaboration-'));
  const cfg = { storage: { type: 'local', local_path: path.join(root, 'storage') }, payments: { enabled: false }, image_proxy: { use_for_video: false }, vendor_lock: { enabled: false } };
  fs.mkdirSync(cfg.storage.local_path);
  const log = { info() {}, warn() {}, error() {}, debug() {}, infow() {}, warnw() {}, errorw() {} };
  let db; let server; let sockets; let base;
  async function start() {
    db = new Database(path.join(root, 'test.db'));
    runMigrationsAndEnsure(db);
    const app = express(); app.use(express.json({ limit: '4mb' })); app.use('/api/v1', setupRouter(cfg, db, log));
    app.use('/static', require('../src/middleware/auth').requireAuth(db), (req, res, next) => {
      const permission = require('../src/services/mediaAuthorizationService').authorizeMediaPath(db, '/static' + req.path, req.auth, { storageRoot: cfg.storage.local_path });
      return permission.allowed ? next() : res.sendStatus(permission.status);
    }, express.static(cfg.storage.local_path));
    server = app.listen(0, '127.0.0.1'); sockets = attach(server, db);
    await once(server, 'listening');
    base = `http://127.0.0.1:${server.address().port}/api/v1`;
  }
  async function stop() {
    for (const socket of sockets.clients) socket.terminate();
    await new Promise(resolve => server.close(resolve)); db.close();
  }
  await start();
  t.after(async () => { await stop(); fs.rmSync(root, { recursive: true, force: true }); });
  const password = crypto.randomBytes(18).toString('base64');
  async function request(token, method, route, data, headers = {}) {
    const res = await fetch(base + route, { method, headers: { 'content-type': 'application/json', 'x-lmd-session': token || '', ...headers }, ...(data === undefined ? {} : { body: JSON.stringify(data) }) });
    return { status: res.status, body: await res.json() };
  }
  async function user(username) {
    const created = auth.createUser(db, { username, password, display_name: username });
    const login = await request('', 'POST', '/auth/login', { username, password });
    assert.equal(login.status, 200);
    return { id: created.id, token: login.body.data.token };
  }
  const owner = await user('project_owner'); const editor = await user('project_editor');
  const viewer = await user('project_viewer'); const stranger = await user('project_stranger');
  const legacyId = Number(db.prepare('INSERT INTO dramas (title,owner_user_id,metadata) VALUES (?,?,?)').run('历史私有项目', owner.id, JSON.stringify({ canvas_layout: { viewport: { x: 11, y: 22, zoom: 0.7 } } })).lastInsertRowid);
  const legacyBefore = (await request(owner.token, 'GET', `/dramas/${legacyId}`)).body.data;
  assert.equal(legacyBefore.permissions.collaboration_enabled, false);
  const created = await request(owner.token, 'POST', '/dramas', { title: '共同编辑', description: '开场' });
  assert.equal(created.status, 201);
  const id = created.body.data.id;
  const prefix = `/dramas/${id}`;
  assert.equal((await request(owner.token, 'PUT', `${prefix}/collaboration/members`, { username: 'project_editor', role: 'editor' })).status, 200);
  assert.equal((await request(owner.token, 'PUT', `${prefix}/collaboration/members`, { username: 'project_viewer', role: 'viewer' })).status, 200);
  assert.equal((await request(stranger.token, 'GET', prefix)).status, 404);
  assert.equal((await request(viewer.token, 'PUT', prefix, { title: '越权' })).status, 403);
  assert.equal((await request(editor.token, 'DELETE', prefix)).status, 403);
  assert.equal((await request(editor.token, 'PUT', prefix, { title: '协作项目' })).status, 200);
  async function uploadImage(token, route, headers = {}) {
    const form = new FormData();
    form.set('drama_id', String(id));
    form.set('file', new Blob([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l9sAAAAASUVORK5CYII=', 'base64')], { type: 'image/png' }), 'fixture.png');
    return fetch(base + route, { method: 'POST', headers: { 'x-lmd-session': token, ...headers }, body: form });
  }
  assert.equal((await uploadImage(viewer.token, '/upload/image')).status, 403);
  assert.equal((await uploadImage(viewer.token, '/media/upload')).status, 403);
  assert.equal((await uploadImage(editor.token, '/upload/image')).status, 200);
  const uploadOperation = { 'x-project-operation': crypto.randomUUID() };
  const firstUpload = await (await uploadImage(editor.token, '/upload/image', uploadOperation)).json();
  assert.deepEqual(await (await uploadImage(editor.token, '/upload/image', uploadOperation)).json(), firstUpload);
  const listed = await request(editor.token, 'GET', '/dramas?membership=joined');
  assert.equal(listed.body.data.items[0].permissions.role, 'editor');
  const read = await request(editor.token, 'GET', `${prefix}/collaboration/text?kind=dramas&id=${id}&field=description`);
  assert.equal(read.status, 200);
  const initial = read.body.data;
  const connect = async token => {
    const socketUrl = base.replace(/^http/, 'ws') + `${prefix}/collaboration/socket`;
    const socket = new WebSocket(socketUrl, { origin: new URL(base).origin, headers: { cookie: `lmd_session=${encodeURIComponent(token)}` } });
    await once(socket, 'open');
    return socket;
  };
  const ownerSocket = await connect(owner.token);
  const editorSocket = await connect(editor.token);
  const sendText = (socket, input) => new Promise((resolve, reject) => {
    const requestId = crypto.randomUUID();
    const timer = setTimeout(() => { socket.off('message', receive); reject(new Error('socket acknowledgement timeout')); }, 3000);
    const receive = bytes => {
      const value = JSON.parse(bytes.toString());
      if (value.request_id !== requestId) return;
      clearTimeout(timer); socket.off('message', receive); resolve(value);
    };
    socket.on('message', receive);
    socket.send(JSON.stringify({ type: 'text_update', request_id: requestId, ...input }));
  });
  const a = new Y.Doc(); const b = new Y.Doc();
  Y.applyUpdate(a, Buffer.from(initial.state, 'base64')); Y.applyUpdate(b, Buffer.from(initial.state, 'base64'));
  const vector = Y.encodeStateVector(a);
  a.getText('content').insert(0, '甲'); b.getText('content').insert(2, '乙');
  const message = doc => ({ kind: 'dramas', id, field: 'description', epoch: initial.epoch, update: Buffer.from(Y.encodeStateAsUpdate(doc, vector)).toString('base64') });
  assert.equal((await sendText(ownerSocket, message(a))).type, 'text');
  assert.equal((await sendText(editorSocket, message(b))).type, 'text');
  assert.equal((await request(editor.token, 'POST', `${prefix}/collaboration/text`, message(b))).status, 200);
  assert.equal((await request(viewer.token, 'POST', `${prefix}/collaboration/text`, message(b))).status, 403);
  assert.equal((await request(owner.token, 'GET', prefix)).body.data.description, '甲开场乙');
  await request(owner.token, 'PUT', prefix, { description: '替换文本' });
  const stale = await request(editor.token, 'POST', `${prefix}/collaboration/text`, message(a));
  assert.equal(stale.status, 409);
  assert.equal(stale.body.error.code, 'DOCUMENT_REPLACED');
  const version = (await request(owner.token, 'GET', prefix)).body.data.revision;
  const operation = { 'x-project-operation': crypto.randomUUID(), 'x-project-revision': String(version) };
  const episodeChange = { creates: [{ episode_number: 1, title: '首集' }] };
  const firstCreate = await request(editor.token, 'PATCH', `${prefix}/collaboration/episodes`, episodeChange, operation);
  assert.equal(firstCreate.status, 200);
  assert.deepEqual((await request(editor.token, 'PATCH', `${prefix}/collaboration/episodes`, episodeChange, operation)).body, firstCreate.body);
  assert.equal((await request(editor.token, 'PATCH', `${prefix}/collaboration/episodes`, { creates: [{ episode_number: 2 }] }, { ...operation, 'x-project-operation': crypto.randomUUID() })).status, 409);
  const baseline = require('../src/services/projectCollaborationService').captureTextBaseline(db, id);
  await request(editor.token, 'PUT', prefix, { description: '人工的新内容' });
  require('../src/services/billingRequestContext').run({ project_text_baseline: baseline }, () => {
    db.prepare('UPDATE dramas SET description=? WHERE id=?').run('延迟生成结果', id);
  });
  assert.equal((await request(owner.token, 'GET', prefix)).body.data.description, '人工的新内容');
  const suggestions = await request(editor.token, 'GET', `${prefix}/collaboration/suggestions`);
  assert.equal(suggestions.body.data[0].proposed_text, '延迟生成结果');
  const applyRoute = `${prefix}/collaboration/suggestions/${suggestions.body.data[0].id}/apply`;
  assert.equal((await request(editor.token, 'POST', applyRoute, { expected_text: '过期内容' })).status, 409);
  assert.equal((await request(editor.token, 'POST', applyRoute, { expected_text: '人工的新内容' })).status, 200);
  await request(owner.token, 'PUT', prefix, { description: '替换文本' });
  fs.writeFileSync(path.join(cfg.storage.local_path, 'sample.txt'), 'durable-media-fixture');
  const source = await request(editor.token, 'POST', '/assets', { name: '独立素材', type: 'audio', local_path: 'sample.txt' });
  assert.equal(source.status, 201);
  const copy = await request(editor.token, 'POST', `${prefix}/collaboration/assets`, { asset_id: source.body.data.id });
  assert.equal(copy.status, 200);
  assert.notEqual(copy.body.data.local_path, 'sample.txt');
  const again = await request(editor.token, 'POST', `${prefix}/collaboration/assets`, { asset_id: source.body.data.id });
  assert.equal(again.body.data.id, copy.body.data.id);
  const episodeId = (await request(editor.token, 'GET', prefix)).body.data.episodes[0].id;
  assert.equal((await request(editor.token, 'PATCH', `${prefix}/collaboration/episodes`, { updates: [{ id: episodeId, fields: { script_content: '雨夜，主角打开一封信。' } }] })).status, 200);
  const shot = await request(editor.token, 'POST', '/storyboards', { episode_id: episodeId, title: '素材引用' });
  assert.equal(shot.status, 201);
  const shotId = shot.body.data.id;
  const scopedBaseline = require('../src/services/projectCollaborationService').captureTextBaseline(db, id, { kind: 'storyboards', id: shotId });
  assert.ok(scopedBaseline.size > 0);
  assert.ok([...scopedBaseline.keys()].every(key => key.startsWith(`storyboards:${shotId}:`)));
  const promptTarget = `kind=storyboards&id=${shotId}&field=universal_segment_text`;
  const promptRefs = [{ asset_id: copy.body.data.id, alias: '声音', occurrence: 0 }];
  assert.equal((await request(editor.token, 'PUT', `/storyboards/${shotId}`, { universal_segment_text: '原始提示词', omni_prompt_document: { text: '原始提示词', refs: promptRefs } })).status, 200);
  const originalPrompt = (await request(editor.token, 'GET', `${prefix}/collaboration/text?${promptTarget}`)).body.data;
  const promptSuggestion = db.prepare('INSERT INTO project_generated_suggestions (drama_id,entity_kind,entity_id,field,proposed_text,created_at) VALUES (?,?,?,?,?,?)')
    .run(id, 'storyboards', shotId, 'universal_segment_text', '应用建议后的提示词', new Date().toISOString()).lastInsertRowid;
  const appliedPrompt = await request(editor.token, 'POST', `${prefix}/collaboration/suggestions/${promptSuggestion}/apply`, { expected_text: originalPrompt.text });
  assert.equal(appliedPrompt.status, 200);
  assert.ok(appliedPrompt.body.data.epoch > originalPrompt.epoch);
  const promptAfterApply = (await request(editor.token, 'GET', `/storyboards/${shotId}`)).body.data;
  assert.equal(promptAfterApply.universal_segment_text, '应用建议后的提示词');
  assert.deepEqual(promptAfterApply.omni_prompt_document, { text: '应用建议后的提示词', refs: promptRefs });
  const refsOnly = await request(editor.token, 'PUT', `/storyboards/${shotId}`, { omni_prompt_document: { refs: [] } });
  assert.equal(refsOnly.status, 200);
  assert.deepEqual(refsOnly.body.data.omni_prompt_document, { text: '应用建议后的提示词', refs: [] });
  assert.equal((await request(editor.token, 'GET', `${prefix}/collaboration/text?${promptTarget}`)).body.data.text, '应用建议后的提示词');
  await stop(); await start();
  const restoredPrompt = (await request(owner.token, 'GET', `/storyboards/${shotId}`)).body.data;
  assert.equal(restoredPrompt.universal_segment_text, '应用建议后的提示词');
  assert.deepEqual(restoredPrompt.omni_prompt_document, { text: '应用建议后的提示词', refs: [] });
  assert.equal((await request(owner.token, 'GET', `${prefix}/collaboration/text?${promptTarget}`)).body.data.text, '应用建议后的提示词');
  const bound = await request(editor.token, 'PUT', `/storyboards/${shotId}`, { audio_local_path: 'sample.txt' });
  assert.equal(bound.status, 200);
  assert.equal((await request(viewer.token, 'GET', `/storyboards/${shotId}`)).body.data.audio_local_path, copy.body.data.local_path);
  assert.equal((await request(editor.token, 'DELETE', `/assets/${copy.body.data.id}`)).status, 409);
  assert.equal((await request(viewer.token, 'GET', `/assets/${copy.body.data.id}`)).body.data.usages[0].storyboard_id, shotId);
  db.prepare('UPDATE storyboards SET audio_local_path=? WHERE id=?').run('sample.txt', shotId);
  const copyCount = db.prepare('SELECT count(*) count FROM project_asset_copies').get().count;
  assert.equal((await request(editor.token, 'PUT', `/storyboards/${shotId}`, { title: '保留旧引用', audio_local_path: 'sample.txt' })).status, 200);
  assert.equal((await request(editor.token, 'GET', `/storyboards/${shotId}`)).body.data.audio_local_path, 'sample.txt');
  assert.equal(db.prepare('SELECT count(*) count FROM project_asset_copies').get().count, copyCount);
  const missing = await request(editor.token, 'POST', '/assets', { name: '缺失本地文件', type: 'image', local_path: 'missing-fixture.png' });
  assert.equal(missing.status, 201);
  assert.equal((await request(editor.token, 'POST', `${prefix}/collaboration/assets`, { asset_id: missing.body.data.id })).status, 409);
  const libraryId = Number(db.prepare('INSERT INTO character_libraries(drama_id,name,image_url,local_path) VALUES (?,?,?,?)').run(id, '历史素材引用', '/static/sample.txt', 'sample.txt').lastInsertRowid);
  assert.equal((await request(editor.token, 'PUT', `/character-library/${libraryId}`, { name: '只改名称', image_url: '/static/sample.txt', local_path: 'sample.txt' })).status, 200);
  assert.equal(db.prepare('SELECT local_path FROM character_libraries WHERE id=?').get(libraryId).local_path, 'sample.txt');
  assert.equal(db.prepare('SELECT count(*) count FROM project_asset_copies').get().count, copyCount);
  let providerCalls = 0;
  let generatedResult;
  let generationTaskId;
  const provider = require('node:http').createServer(async (req, res) => {
    req.resume();
    await once(req, 'end');
    providerCalls++;
    assert.equal(db.prepare("SELECT COUNT(*) n FROM billing_transactions WHERE type='authorization' AND user_id=?").get(editor.id).n, 1);
    await request(editor.token, 'PUT', `/storyboards/${shotId}`, { title: '生成期间人工修改' });
    const content = JSON.stringify([{ shot_number: 1, title: '生成的新分镜', duration: 5, action: '打开信封', characters: [] }]);
    res.writeHead(200, { 'content-type': 'text/event-stream', 'x-request-id': 'fixture-collaboration-text' });
    res.end(`data: ${JSON.stringify({ id: 'fixture-collaboration-text', choices: [{ delta: { content }, finish_reason: 'stop' }], usage: { prompt_tokens: 7, completion_tokens: 3, total_tokens: 10 } })}\n\ndata: [DONE]\n\n`);
  });
  provider.listen(0, '127.0.0.1'); await once(provider, 'listening');
  try {
    const model = 'fixture-collaboration-text';
    require('../src/services/aiConfigService').createConfig(db, log, { name: model, service_type: 'text', provider: 'fixture', api_protocol: 'openai', base_url: `http://127.0.0.1:${provider.address().port}`, endpoint: '/chat/completions', api_key: 'fixture-only', model: [model], default_model: model, is_default: true });
    const admin = auth.createUser(db, { username: 'fixture_billing_admin', password, account_kind: 'platform_admin' });
    const billing = require('../src/services/billingService');
    const book = db.prepare("SELECT id FROM billing_price_books WHERE status='published' ORDER BY id LIMIT 1").get();
    const now = new Date().toISOString();
    for (const meter of ['input_token', 'output_token']) db.prepare('INSERT INTO billing_price_book_items (price_book_id,service_type,model,meter,unit_price_micro,is_free,created_at,updated_at) VALUES (?,?,?,?,?,0,?,?)').run(book.id, 'text', model, meter, 1, now, now);
    billing.adjustBalance(db, admin.id, editor.id, 10000, 'isolated collaboration test');
    const route = `/episodes/${episodeId}/storyboards`;
    assert.equal((await request('', 'POST', route, { model })).status, 401);
    assert.equal((await request(viewer.token, 'POST', route, { model })).status, 403);
    assert.equal((await request(stranger.token, 'POST', route, { model })).status, 404);
    assert.equal(providerCalls, 0);
    const headers = { 'x-project-operation': crypto.randomUUID() };
    const generated = await request(editor.token, 'POST', route, { model }, headers);
    assert.equal(generated.status, 200, JSON.stringify(generated.body));
    generationTaskId = generated.body.data.task_id;
    assert.deepEqual((await request(editor.token, 'POST', route, { model }, headers)).body, generated.body);
    let task;
    for (let n = 0; n < 200; n++) {
      task = (await request(editor.token, 'GET', `/tasks/${generationTaskId}`)).body.data;
      if (['completed', 'failed'].includes(task?.status)) break;
      await new Promise(resolve => setTimeout(resolve, 25));
    }
    assert.equal(task.status, 'completed', JSON.stringify(task));
    generatedResult = JSON.parse(task.result);
    assert.equal(providerCalls, 1);
    const usage = db.prepare('SELECT * FROM billing_usage_logs WHERE user_id=? AND model=?').all(editor.id, model);
    assert.equal(usage.length, 1);
    assert.deepEqual(JSON.parse(usage[0].usage_json), { input_token: 7, output_token: 3 });
    assert.equal(db.prepare("SELECT COUNT(*) n FROM billing_transactions WHERE type='settlement' AND authorization_id=?").get(usage[0].authorization_id).n, 1);
  } finally {
    await new Promise(resolve => provider.close(resolve));
  }
  assert.equal(generatedResult.requires_application, true);
  assert.equal((await request(editor.token, 'GET', `/storyboards/${shotId}`)).body.data.title, '生成期间人工修改');
  const proposalRoute = `${prefix}/collaboration/suggestions/${generatedResult.suggestion_id}`;
  const proposed = (await request(editor.token, 'GET', proposalRoute)).body.data;
  assert.equal((await request(editor.token, 'POST', `${proposalRoute}/apply`, { expected_text: 'stale' })).status, 409);
  assert.equal((await request(editor.token, 'POST', `${proposalRoute}/apply`, { expected_text: proposed.current_text })).status, 200);
  assert.equal((await request(editor.token, 'GET', `/storyboards/${shotId}`)).body.data.title, '生成的新分镜');
  const removable = (await request(editor.token, 'POST', '/storyboards', { episode_id: episodeId, title: '待删除镜头' })).body.data;
  const deletedDocument = (await request(editor.token, 'GET', `${prefix}/collaboration/text?kind=storyboards&id=${removable.id}&field=description`)).body.data;
  const beforeDeleteRevision = (await request(editor.token, 'GET', prefix)).body.data.revision;
  assert.equal((await request(owner.token, 'DELETE', `/storyboards/${removable.id}`)).status, 200);
  assert.equal((await request(editor.token, 'POST', `${prefix}/collaboration/text`, { kind: 'storyboards', id: removable.id, field: 'description', epoch: deletedDocument.epoch, update: deletedDocument.state })).status, 404);
  assert.equal((await request(editor.token, 'PUT', '/storyboards/reorder', { episode_id: episodeId, ids: [removable.id, shotId] }, { 'x-project-operation': crypto.randomUUID(), 'x-project-revision': String(beforeDeleteRevision) })).status, 409);
  assert.equal((await request(viewer.token, 'GET', `/assets/${copy.body.data.id}`)).status, 200);
  const mediaRequest = token => fetch(base.replace('/api/v1', '') + '/static/' + copy.body.data.local_path, { headers: { 'x-lmd-session': token } });
  assert.equal(await (await mediaRequest(viewer.token)).text(), 'durable-media-fixture');
  assert.equal((await request(viewer.token, 'GET', `/assets/${source.body.data.id}`)).status, 404);
  await request(editor.token, 'DELETE', `/assets/${source.body.data.id}`);
  fs.unlinkSync(path.join(cfg.storage.local_path, 'sample.txt'));
  assert.equal(fs.readFileSync(path.join(cfg.storage.local_path, copy.body.data.local_path), 'utf8'), 'durable-media-fixture');
  const revoked = once(await connect(editor.token), 'close');
  const shotBaseline = (await request(owner.token, 'GET', `/storyboards/${shotId}`)).body.data;
  assert.equal((await request(owner.token, 'GET', `/episodes/${episodeId}/generation-settings`)).status, 200);
  const settingsReadRevision = (await request(owner.token, 'GET', prefix)).body.data.revision;
  assert.equal((await request(owner.token, 'GET', `/episodes/${episodeId}/generation-settings`)).status, 200);
  assert.equal((await request(owner.token, 'GET', prefix)).body.data.revision, settingsReadRevision);
  assert.equal((await request(owner.token, 'PUT', `/storyboards/${shotId}`, { description: '自己刚保存的分镜文字' })).status, 200);
  const expectedAudio = { version: 1, checks: [{ kind: 'storyboards', id: shotId, fields: { audio_volume: shotBaseline.audio_volume } }] };
  assert.equal((await request(owner.token, 'PUT', `/storyboards/${shotId}`, { audio_volume: 0.7, _project_edit: expectedAudio })).status, 200);
  assert.equal((await request(editor.token, 'PUT', `/storyboards/${shotId}`, { audio_volume: 0.4 })).status, 200);
  assert.equal((await request(owner.token, 'PUT', `/storyboards/${shotId}`, { audio_volume: 0.9, _project_edit: expectedAudio })).status, 409);
  const layoutBaseline = (await request(owner.token, 'GET', prefix)).body.data.revision;
  const layoutHeaders = revision => ({ 'x-project-operation': crypto.randomUUID(), 'x-project-revision': String(revision) });
  const collaboratorLayout = { version: 1, nodes: { a: { x: 100, y: 0 }, b: { x: 0, y: 0 } } };
  assert.equal((await request(editor.token, 'PUT', `${prefix}/canvas-layout`, { canvas_layout: collaboratorLayout }, layoutHeaders(layoutBaseline))).status, 200);
  const staleLayout = { version: 1, nodes: { a: { x: 0, y: 0 }, b: { x: 100, y: 0 } } };
  assert.equal((await request(owner.token, 'PUT', `${prefix}/canvas-layout`, { canvas_layout: staleLayout }, layoutHeaders(layoutBaseline))).status, 409);
  const refreshedLayout = (await request(owner.token, 'GET', prefix)).body.data;
  assert.deepEqual(refreshedLayout.metadata.canvas_layout.nodes, collaboratorLayout.nodes);
  const mergedLayout = { version: 1, nodes: { a: { x: 100, y: 0 }, b: { x: 100, y: 0 } } };
  assert.equal((await request(owner.token, 'PUT', `${prefix}/canvas-layout`, { canvas_layout: mergedLayout }, layoutHeaders(refreshedLayout.revision))).status, 200);
  assert.equal((await request(owner.token, 'DELETE', `${prefix}/collaboration/members/${editor.id}`)).status, 200);
  assert.equal((await revoked)[0], 4403);
  assert.equal((await request(editor.token, 'GET', prefix)).status, 404);
  assert.equal((await request(editor.token, 'GET', `/assets/${copy.body.data.id}`)).status, 404);
  assert.equal((await mediaRequest(editor.token)).status, 404);
  await stop(); await start();
  const legacyAfter = (await request(owner.token, 'GET', `/dramas/${legacyId}`)).body.data;
  assert.equal(legacyAfter.title, legacyBefore.title);
  assert.deepEqual(legacyAfter.metadata, legacyBefore.metadata);
  assert.equal(legacyAfter.permissions.collaboration_enabled, false);
  assert.equal((await request(viewer.token, 'GET', `/dramas/${legacyId}`)).status, 404);
  assert.equal((await request(owner.token, 'GET', prefix)).body.data.description, '替换文本');
  assert.deepEqual((await request(owner.token, 'GET', prefix)).body.data.metadata.canvas_layout.nodes, mergedLayout.nodes);
  assert.equal((await request(owner.token, 'GET', `/storyboards/${shotId}`)).body.data.audio_volume, 0.4);
  assert.equal((await request(viewer.token, 'GET', `/assets/${copy.body.data.id}`)).status, 200);
  assert.equal(await (await mediaRequest(viewer.token)).text(), 'durable-media-fixture');
  assert.equal((await request(owner.token, 'GET', `/tasks/${generationTaskId}`)).body.data.status, 'completed');
  assert.equal(providerCalls, 1, 'restart must not repeat the provider call');
  const disableOwnerSocket = await connect(owner.token);
  const disableViewerSocket = await connect(viewer.token);
  const ownerClosed = once(disableOwnerSocket, 'close');
  const viewerClosed = once(disableViewerSocket, 'close');
  const beforeDisable = (await request(owner.token, 'GET', prefix)).body.data;
  const beforeTask = db.prepare('SELECT * FROM async_tasks WHERE id=?').get(generationTaskId);
  const episodeBefore = db.prepare('SELECT * FROM episodes WHERE id=?').get(episodeId);
  const textTarget = { kind: 'episodes', id: episodeId, field: 'script_content' };
  const textBefore = (await request(owner.token, 'GET', `${prefix}/collaboration/text?kind=episodes&id=${episodeId}&field=script_content`)).body.data;
  const offlineDoc = new Y.Doc();
  Y.applyUpdate(offlineDoc, Buffer.from(textBefore.state, 'base64'));
  offlineDoc.getText('content').insert(0, 'HTTP确认的新稿');
  const offlineInput = { ...textTarget, epoch: textBefore.epoch, update: Buffer.from(Y.encodeStateAsUpdate(offlineDoc)).toString('base64') };
  assert.equal((await request(owner.token, 'POST', `${prefix}/collaboration/text`, offlineInput)).status, 200);
  const savedText = offlineDoc.getText('content').toString();
  offlineDoc.destroy();
  assert.equal((await request(viewer.token, 'POST', `${prefix}/collaboration/disable`, {})).status, 403);
  assert.equal((await request(stranger.token, 'POST', `${prefix}/collaboration/disable`, {})).status, 404);
  assert.equal((await request(owner.token, 'POST', `${prefix}/collaboration/disable`, {})).status, 200);
  assert.equal((await ownerClosed)[0], 4403);
  assert.equal((await viewerClosed)[0], 4403);
  assert.equal((await request(viewer.token, 'GET', prefix)).status, 404);
  assert.equal((await request(viewer.token, 'GET', `/assets/${copy.body.data.id}`)).status, 404);
  assert.equal((await mediaRequest(viewer.token)).status, 404);
  assert.equal((await request(viewer.token, 'GET', `/tasks/${generationTaskId}`)).status, 404);
  assert.equal((await request(owner.token, 'POST', `${prefix}/collaboration/text`, offlineInput)).status, 409);
  assert.ok(!(await request(viewer.token, 'GET', '/dramas?membership=joined')).body.data.items.some(project => project.id === id));
  const disabledRevision = (await request(owner.token, 'GET', prefix)).body.data.revision;
  assert.equal((await request(owner.token, 'POST', `${prefix}/collaboration/disable`, {})).status, 200);
  assert.equal((await request(owner.token, 'GET', prefix)).body.data.revision, disabledRevision);
  await stop(); await start();
  const disabled = (await request(owner.token, 'GET', prefix)).body.data;
  assert.equal(disabled.permissions.collaboration_enabled, false);
  assert.deepEqual(disabled.members, beforeDisable.members);
  assert.deepEqual(db.prepare('SELECT * FROM async_tasks WHERE id=?').get(generationTaskId), beforeTask);
  assert.equal(disabled.episodes.find(ep => ep.id === episodeId).script_content, savedText);
  assert.equal((await request(owner.token, 'PUT', `${prefix}/episode-edits`, { mode: 'update', episodes: [{ id: episodeId, title: episodeBefore.title, expected_title: episodeBefore.title, expected_script_content: savedText, script_content: '关闭后普通保存' }] })).status, 200);
  assert.equal((await request(owner.token, 'POST', `${prefix}/collaboration/enable`, {})).status, 200);
  const restored = (await request(viewer.token, 'GET', prefix)).body.data;
  assert.equal(restored.permissions.collaboration_enabled, true);
  assert.ok(restored.revision > disabledRevision);
  const restoredText = (await request(owner.token, 'GET', `${prefix}/collaboration/text?kind=episodes&id=${episodeId}&field=script_content`)).body.data;
  assert.equal(restoredText.text, '关闭后普通保存');
  assert.ok(restoredText.epoch > textBefore.epoch);
  assert.equal((await request(owner.token, 'POST', `${prefix}/collaboration/text`, offlineInput)).status, 409);
  assert.equal(await (await mediaRequest(viewer.token)).text(), 'durable-media-fixture');
  assert.equal(providerCalls, 1, 'disable, reenable and restart never resubmit tasks');
  const characterId = Number(db.prepare('INSERT INTO characters(drama_id,name) VALUES (?,?)').run(id, '历史角色').lastInsertRowid);
  const sceneId = Number(db.prepare('INSERT INTO scenes(drama_id,location) VALUES (?,?)').run(id, '历史场景').lastInsertRowid);
  const propId = Number(db.prepare('INSERT INTO props(drama_id,name) VALUES (?,?)').run(id, '历史道具').lastInsertRowid);
  assert.equal((await request(owner.token, 'DELETE', prefix)).status, 200);
  await stop(); await start();
  for (const route of [`/characters/${characterId}`, `/scenes/${sceneId}`, `/props/${propId}`, `/storyboards/${shotId}`, `/assets/${copy.body.data.id}`]) {
    assert.equal((await request(owner.token, 'GET', route)).status, 200, route);
    assert.equal((await request(viewer.token, 'GET', route)).status, 404, route);
    assert.equal((await request(stranger.token, 'GET', route)).status, 404, route);
  }
  assert.equal((await request(editor.token, 'GET', `/tasks/${generationTaskId}`)).body.data.status, 'completed');
  assert.equal((await request(viewer.token, 'GET', `/tasks/${generationTaskId}`)).status, 404);
  assert.equal((await request(owner.token, 'PUT', `/characters/${characterId}`, { name: '禁止修改已删除项目' })).status, 404);
  a.destroy(); b.destroy();
});
