import request from '@/utils/request'

export const accountAPI = {
  me: () => request.get('/billing/me'),
  transactions: (params) => request.get('/billing/transactions', { params }),
  usage: (params) => request.get('/billing/usage', { params }),
  quoteResourceImages: (data) => request.post('/billing/resource-image-quotes', data),
  usageMembers: () => request.get('/billing/usage-members'),
  models: () => request.get('/models/available'),
  changePassword: (data) => request.post('/auth/change-password', data),
  changeUsername: (data) => request.patch('/auth/username', data),
  changeDisplayName: (data) => request.patch('/auth/display-name', data),
}

export const adminAPI = {
  users: () => request.get('/admin/users'),
  createUser: (data) => request.post('/admin/users', data),
  updateUser: (id, data) => request.patch(`/admin/users/${id}`, data),
  adjustBalance: (id, data) => request.post(`/admin/users/${id}/balance-adjustments`, data),
  correctBalance: (id, data) => request.post(`/admin/users/${id}/balance-corrections`, data),
  tenants: () => request.get('/admin/tenants'),
  tenant: (id) => request.get(`/admin/tenants/${id}`),
  createTenant: (data) => request.post('/admin/tenants', data),
  updateTenant: (id, data) => request.patch(`/admin/tenants/${id}`, data),
  setTenantMember: (tenantId, userId, data) => request.put(`/admin/tenants/${tenantId}/members/${userId}`, data),
  replaceTenantBindings: (id, data) => request.put(`/admin/tenants/${id}/bindings`, data),
  customerOrganizations: () => request.get('/admin/customer-organizations'),
  customerOrganization: (id) => request.get(`/admin/customer-organizations/${id}`),
  createCustomerOrganization: (data) => request.post('/admin/customer-organizations', data),
  updateCustomerOrganization: (id, data) => request.patch(`/admin/customer-organizations/${id}`, data),
  replaceCustomerOrganizationMembers: (id, data) => request.put(`/admin/customer-organizations/${id}/members`, data),
  adjustCustomerOrganizationBalance: (id, data) => request.post(`/admin/customer-organizations/${id}/balance-adjustments`, data),
  priceBooks: () => request.get('/admin/price-books'),
  createPriceBook: (data) => request.post('/admin/price-books', data),
  updatePriceBook: (id, data) => request.patch(`/admin/price-books/${id}`, data),
  probeVolcenginePrices: (data = {}) => request.post('/admin/provider-prices/volcengine/probe', data),
  volcenginePriceProbeStatus: () => request.get('/admin/provider-prices/volcengine/probe'),
  syncVolcenginePrices: () => request.post('/admin/provider-prices/volcengine/sync'),
  providerPriceSyncs: (params) => request.get('/admin/provider-price-syncs', { params }),
  providerPriceSync: (id) => request.get(`/admin/provider-price-syncs/${id}`),
  updateProviderPriceCandidate: (syncId, candidateId, data) => request.patch(`/admin/provider-price-syncs/${syncId}/candidates/${candidateId}`, data),
  createProviderPriceDraft: (id) => request.post(`/admin/provider-price-syncs/${id}/create-draft`),
  notices: (params) => request.get('/admin/notices', { params }),
  archiveNotice: (id) => request.post(`/admin/notices/${id}/archive`),
  publishPriceBook: (id, data) => request.post(`/admin/price-books/${id}/publish`, data),
  rollbackPriceBook: (id, data) => request.post(`/admin/price-books/${id}/rollback`, data),
  transactions: (params) => request.get('/admin/transactions', { params }),
  usage: (params) => request.get('/admin/usage', { params }),
  usageSummary: (params) => request.get('/admin/usage-summary', { params }),
  projectUsage: (params) => request.get('/admin/project-usage', { params }),
  projectUsageDetail: (id, params) => request.get(`/admin/project-usage/${id}`, { params }),
  unassignedProjectUsage: (params) => request.get('/admin/project-usage/unassigned', { params }),
  overview: (params) => request.get('/admin/overview', { params }),
  operationAlertSettings: () => request.get('/admin/operations-alert-settings'),
  saveOperationAlertSettings: (data) => request.patch('/admin/operations-alert-settings', data),
  productionExport: (params) => request.get('/admin/production-export', { params, responseType: 'blob' }),
  operationReports: (params) => request.get('/admin/operations-reports', { params }),
  production: (params) => request.get('/admin/production', { params }),
  productionDetail: (id) => request.get(`/admin/production/${id}`),
  retryProductionPostprocess: (id, data) => request.post(`/admin/production/${id}/retry-postprocess`, data),
  adoptProductionSource: (id, data) => request.post(`/admin/production/${id}/adopt-source`, data),
  retryProductionArchive: (id, data) => request.post(`/admin/production/${id}/retry-archive`, data),
  mediaArchives: (params) => request.get('/admin/media-archives', { params }),
  reconciliations: (params) => request.get('/admin/billing-reconciliations', { params }),
  audit: (params) => request.get('/admin/audit-logs', { params }),
}
