import request from '@/utils/request'
const base = '/admin/costs'
export const costsAPI = {
  summary: params => request.get(`${base}/summary`, { params }),
  breakdown: params => request.get(`${base}/breakdown`, { params }),
  calls: params => request.get(`${base}/calls`, { params }),
  call: id => request.get(`${base}/calls/${id}`),
  reprice: (id, reason) => request.post(`${base}/calls/${id}/reprice`, { reason }),
  previewReprice: data => request.post(`${base}/reprices/preview`, data),
  executeReprice: (id, reason) => request.post(`${base}/reprices/${id}/execute`, { confirm: true, reason }),
  accounts: () => request.get(`${base}/accounts`),
  createAccount: data => request.post(`${base}/accounts`, data),
  bind: (account, config) => request.put(`${base}/accounts/${account}/bindings/${config}`),
  prices: () => request.get(`${base}/prices`),
  draft: data => request.post(`${base}/prices`, data),
  publish: id => request.post(`${base}/prices/${id}/publish`, { confirm: true }),
  fetchPrices: data => request.post(`${base}/price-sources/fetch`, data),
  sources: () => request.get(`${base}/price-sources`),
  source: id => request.get(`${base}/price-sources/${id}`),
  reports: params => request.get(`${base}/reports`, { params }),
  report: id => request.get(`${base}/reports/${id}`),
  saveReport: data => request.post(`${base}/reports`, data),
  backfills: () => request.get(`${base}/backfills`),
  backfill: id => request.get(`${base}/backfills/${id}`),
  preview: data => request.post(`${base}/backfills/preview`, data),
  execute: id => request.post(`${base}/backfills/${id}/execute`, { confirm: true }),
}
