import test from 'node:test'
import assert from 'node:assert/strict'
import { extractRealPersonContentIndex, extractRequestId, generationFailureCopyText, presentGenerationFailure, shortRequestId } from '../src/utils/generationFailure.js'
const requestId = '02178652123456789abcdef0123456789be64'
test('extracts and shortens a Volcengine request ID without losing the full value', () => { assert.equal(extractRequestId(`failed. Request id: ${requestId}, clientIP: 127.0.0.1`), requestId); assert.equal(shortRequestId(requestId), '02178652…89be64') })
test('maps real-person and model permission failures to clear user actions', () => { const person = presentGenerationFailure({ error_msg: `input image content[1] may contain real person. Request id: ${requestId}` }); assert.equal(person.title, '真人素材需要授权'); assert.match(person.action, /授权/); assert.equal(person.requestId, requestId); const permission = presentGenerationFailure({ error_msg: 'Your account has not activated the model seedance. Request id: abcdef-123456' }); assert.equal(permission.title, '当前模型未开通'); assert.match(permission.action, /管理员/) })
test('maps a provider content index to the one-based reference image number', () => { assert.equal(extractRealPersonContentIndex("input image 'content[5]' may contain real person"), 5); assert.equal(presentGenerationFailure({ error_msg: 'input image content[5] may contain real person' }).realPersonContentIndex, 5); assert.equal(extractRealPersonContentIndex('another error'), null) })
test('maps common local snapshot failures and keeps unknown raw reasons', () => { assert.equal(presentGenerationFailure({ error_msg: 'camera_fixed is not supported for model x in t2v' }).title, '当前模型不支持此参数'); assert.equal(presentGenerationFailure({ error_msg: 'API key is forbidden by IP whitelist setting' }).title, '服务访问地址不在白名单中'); assert.equal(presentGenerationFailure({ error_msg: 'fetch failed: ECONNRESET' }).title, '模型服务连接失败'); const unknown = presentGenerationFailure({ error_msg: 'provider returned a new error' }); assert.equal(unknown.title, '视频生成失败'); assert.equal(unknown.rawReason, 'provider returned a new error') })
test('distinguishes an Ark internal material timeout from a user asset download failure', () => { const internal = presentGenerationFailure({ error_msg: 'Timeout while downloading url: https://ark-common-storage-prod-cn-beijing.tos-cn-beijing.volces.com/ark-async-gateway/cgt-test/2?x-tos-process=image%2Fformat%2Cjpg Request id: 021788' }); assert.equal(internal.title, '模型内部素材读取超时'); assert.match(internal.action, /原配置重试/); assert.match(internal.action, /无需重新上传/); const input = presentGenerationFailure({ error_msg: 'failed to download input image https://customer.example/reference.png' }); assert.equal(input.title, '参考素材读取失败') })
test('copy text contains the full response ID and original reason', () => { const copied = generationFailureCopyText({ id: 42, error_msg: `failed. Request id: ${requestId}` }); assert.match(copied, /本地任务 ID: 42/); assert.match(copied, new RegExp(requestId)); assert.match(copied, /原始失败原因:/) })
test('status-only failures keep the existing recovery path', () => { assert.equal(presentGenerationFailure({ status: 'unknown' }).title, '任务状态暂不可用'); assert.match(presentGenerationFailure({ status: 'billing_reconciliation' }).action, /不要重复提交/); assert.match(presentGenerationFailure({ status: 'invalid' }).action, /管理员/) })
