import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const freeCreate = readFileSync(new URL('../src/views/FreeCreate.vue', import.meta.url), 'utf8')
const promptEditor = readFileSync(new URL('../src/components/OmniAssetPromptEditor.vue', import.meta.url), 'utf8')
const universalEditor = readFileSync(new URL('../src/components/UniversalSegmentOmniAtEditor.vue', import.meta.url), 'utf8')
const filmCreate = readFileSync(new URL('../src/views/FilmCreate.vue', import.meta.url), 'utf8')
const adminConsole = readFileSync(new URL('../src/views/AdminConsole.vue', import.meta.url), 'utf8')
const mediaLibrary = readFileSync(new URL('../src/views/MediaLibrary.vue', import.meta.url), 'utf8')
const historyDetail = readFileSync(new URL('../src/views/GenerationHistoryDetail.vue', import.meta.url), 'utf8')
const router = readFileSync(new URL('../src/router/index.js', import.meta.url), 'utf8')
const dragPreview = readFileSync(new URL('../src/utils/dragPreview.js', import.meta.url), 'utf8')
const pointerDrag = readFileSync(new URL('../src/utils/assetPointerDrag.js', import.meta.url), 'utf8')
const canvasEpisodeGenerate = readFileSync(new URL('../src/composables/useCanvasEpisodeGenerate.js', import.meta.url), 'utf8')
const canvasWorkflowRunner = readFileSync(new URL('../src/composables/useCanvasWorkflowRunner.js', import.meta.url), 'utf8')

test('storyboard navigation uses real video, including retained source after post-processing failure', () => {
  assert.match(freeCreate, /<video v-if="shot\.video_url"/)
  assert.match(freeCreate, /v-else class="shot-video-placeholder"/)
  assert.match(freeCreate, /class="shot-play">▶/)
  assert.match(freeCreate, /const preservedVideo = currentShot\.value\.video_url/)
  assert.match(freeCreate, /source_local_path/)
  assert.match(freeCreate, /function bestPlayableVideo/)
  assert.match(freeCreate, /currentShot\.value\.video_url = localVideoUrl\(playableVideo\)/)
  assert.match(freeCreate, /videosAPI\.list\(\{\s*storyboard_id: storyboard\.id,\s*page_size: 20/)
  assert.doesNotMatch(freeCreate, /storyboard_id: storyboard\.id,\s*episode_id:/)
  assert.doesNotMatch(freeCreate, /storyboard-placeholder\.svg|shotCover\(/)
})

test('storyboard preview controls stay hidden until a playable video exists', () => {
  assert.match(freeCreate, /<template v-if="activeVideoUrl && !previewVideoError && !previewVideoProgress">\s*<div class="player-tools"/)
  assert.match(freeCreate, /<div class="video-stage has-video"/)
  assert.match(freeCreate, /<section v-else class="generation-stage-status"/)
  assert.match(freeCreate, /generation-error-copy/)
  assert.match(freeCreate, /完成生成后，播放器和成片操作将在这里显示/)
})

test('development mode can preview the video error state without creating a task', () => {
  assert.match(freeCreate, /const videoStatusPreviewEnabled = import\.meta\.env\.DEV/)
  assert.match(freeCreate, /@click="previewVideoError = true; previewVideoProgress = false">预览错误状态/)
  assert.match(freeCreate, /开发预览不会创建任务，也不会调用模型服务/)
  assert.match(freeCreate, /GenerationFailureDetails :job="previewVideoErrorJob"/)
  assert.match(freeCreate, /@click="previewVideoError = false">退出错误预览/)
  assert.match(freeCreate, /activeVideoUrl && !previewVideoError && !previewVideoProgress/)
  assert.match(freeCreate, /预览真人授权提示/)
  assert.match(freeCreate, /watch\(activeShotId, \(\) => \{ previewVideoError\.value = false; previewVideoProgress\.value = false \}\)/)
})

test('development mode can preview indeterminate provider progress without creating a task', () => {
  assert.match(freeCreate, /预览生成进度/)
  assert.match(freeCreate, /generation-progress is-indeterminate/)
  assert.match(freeCreate, /模型服务正在生成视频/)
  assert.match(freeCreate, /@click="previewVideoProgress = false">退出进度预览/)
})

test('generation actions use a synchronous single-flight guard before requests', () => {
  assert.match(freeCreate, /if \(creating\.value \|\| hasActiveShotGeneration\.value\) return; creating\.value = true/)
  assert.match(freeCreate, /const hasActiveShotGeneration = computed/)
  assert.match(filmCreate, /if \(isSbVideoGenerating\(sb\.id\)\) return\s+submittingSbVideoIds\.add\(sb\.id\)/)
  assert.match(filmCreate, /if \(generatingSbImageIds\.has\(sb\.id\) \|\| genStore\.isRunning\(meta\)\) return/)
  assert.match(filmCreate, /if \(genStore\.isRunning\(meta\)\) return\s+genStore\.markRunning\(meta\)/)
})

test('an empty episode shows one explicit empty state instead of a phantom first shot', () => {
  assert.match(freeCreate, /<template v-if="currentShot">/)
  assert.match(freeCreate, /<section v-else class="empty-shot-workspace"/)
  assert.match(freeCreate, /当前剧集还没有分镜/)
  assert.match(freeCreate, /@click="addShot\(false\)">添加第一个镜头/)
  assert.match(freeCreate, /:disabled="!currentShot \|\| reproductionMode" @click="addShot\(true\)">当前镜头后添加/)
  assert.match(freeCreate, /const workspaceReady = ref\(false\)/)
  assert.match(freeCreate, /finally \{ workspaceReady\.value = true \}/)
})

test('batch media actions distinguish empty, completed and missing-reference states', () => {
  assert.match(canvasEpisodeGenerate, /if \(!boards\.length\) \{\s*ElMessage\.warning\(\{ message: '当前集还没有分镜，请先生成或新建分镜', grouping: true \}\)/)
  assert.match(canvasEpisodeGenerate, /if \(!imageBoards\.length\) \{\s*ElMessage\.info\(\{ message: '当前集只有全能模式分镜，无需生图，请直接生视频', grouping: true \}\)/)
  assert.match(canvasEpisodeGenerate, /当前集经典模式分镜均已有图片，无需重复生成/)
  assert.match(canvasEpisodeGenerate, /当前集分镜均已有视频，无需重复生成/)
  assert.match(canvasEpisodeGenerate, /missingPromptCount = missingImages\.length - todo\.length/)
  assert.match(canvasEpisodeGenerate, /缺少图片提示词，将跳过/)
  assert.match(canvasEpisodeGenerate, /missingInputCount = incomplete\.length - todo\.length/)
  assert.match(canvasEpisodeGenerate, /缺少生成输入，将跳过/)
  assert.match(canvasWorkflowRunner, /export function canRunVideoStep/)
  assert.match(filmCreate, /if \(boards\.length === 0\) \{\s*ElMessage\.warning\(\{ message: '当前集还没有分镜，请先生成或新建分镜', grouping: true \}\)/)
  assert.match(filmCreate, /completedVideoCount === boards\.length/)
  assert.match(filmCreate, /当前集分镜缺少可用参考图，请先生成或选择分镜图/)
  assert.match(filmCreate, /没有可生成视频的分镜：\$\{completedVideoCount\} 镜已有视频，\$\{missingReferenceCount\} 镜缺少参考图/)
})

test('clicking a completed history record previews it without changing the adopted version', () => {
  assert.match(freeCreate, /function selectHistoryJob\(job\) \{ playOnSelection\.value = true; selectedHistoryJobId\.value = job\.id \}/)
  assert.match(freeCreate, /return selected \|\| adopted \|\| bound \|\| shotHistory\.value\[0\] \|\| null/)
})

test('project storyboard history opens a complete detail page with the original prompt', () => {
  assert.match(freeCreate, /aria-label="复制镜头" @click\.stop="copyShot\(shot\)"/)
  assert.doesNotMatch(freeCreate, />复制当前镜头<\/el-button>/)
  assert.doesNotMatch(freeCreate, /aria-label="上移镜头"|aria-label="下移镜头"/)
  assert.match(freeCreate, /const copied = await storyboardsAPI\.copy\(currentShot\.value\.id\)/)
  assert.match(freeCreate, /@click\.stop="openHistoryDetail\(job\)">查看生成详情/)
  assert.match(freeCreate, /@click="openHistoryDetail\(activeJob\)">查看本版本详情/)
  assert.match(freeCreate, /original_prompt: snapshot\.original_prompt \|\| snapshot\.prompt/)
  assert.match(freeCreate, /path: `\/generation-history\/\$\{generationId\}`/)
  assert.doesNotMatch(freeCreate, /historyPromptOpen|historyPromptText|viewHistoryPrompt/)
  assert.match(router, /path: '\/generation-history\/:id'/)
  assert.match(historyDetail, /<b>原始提示词<\/b>/)
  assert.match(historyDetail, /模型实际接收的提示词/)
  assert.match(historyDetail, /实际扣费/)
  assert.match(historyDetail, /请求分辨率/)
  assert.match(historyDetail, /输出分辨率/)
  assert.match(historyDetail, /omniVideoAPI\.historyDetail\(route\.params\.id\)/)
  assert.match(filmCreate, />复制当前分镜<\/el-button>/)
  assert.match(filmCreate, /storyboardsAPI\.copy\(sb\.id\)/)
  assert.match(filmCreate, /生成结果和历史记录未复制/)
  assert.match(filmCreate, /function getDisplayedSbVideoPrompt\(sb\)/)
  assert.match(filmCreate, /getSbVideo\(sb\.id\)\?\.prompt \|\| sb\.video_prompt/)
  assert.match(filmCreate, /item\.video\?\.prompt \? `生成提示词：\$\{item\.video\.prompt\}`/)
})

test('storyboard media management keeps project scope and returns to its source page', () => {
  assert.match(freeCreate, /function openMediaLibrary\(\)/)
  assert.match(freeCreate, /drama_id: targetDramaId/)
  assert.match(freeCreate, /return_to: route\.fullPath/)
  assert.match(freeCreate, /@click="openMediaLibrary">管理素材/)
  assert.match(filmCreate, /function openProjectMediaLibrary\(\)/)
  assert.match(filmCreate, /return_to: route\.fullPath/)
  assert.match(mediaLibrary, /@click="returnToSource"/)
  assert.match(mediaLibrary, /safeRedirectPath\(rawReturnTo, ''\)/)
  assert.match(mediaLibrary, /path: `\/film\/\$\{projectDramaId\.value\}`/)
  assert.doesNotMatch(mediaLibrary, /@click="\$router\.push\('\/'\)">[\s\S]{0,100}返回/)
})

test('provider internal material timeout can retry from the immutable snapshot', () => {
  assert.match(freeCreate, /activeJob\.status === 'retryable' \|\| activeJob\.can_retry_generation/)
  assert.match(freeCreate, /job\.status === 'retryable' \|\| job\.can_retry_generation/)
  assert.match(freeCreate, /使用原配置重试/)
  assert.match(freeCreate, /omniVideoAPI\.retry\(job\.id\)/)
})

test('admin production detail opens an immutable workbench reproduction snapshot', () => {
  assert.match(adminConsole, /<h3>完整提示词<\/h3>/)
  assert.match(adminConsole, /请求素材/)
  assert.match(adminConsole, /在制作台复现/)
  assert.match(adminConsole, /replay_generation_id: replay\.video_generation_id/)
  assert.match(adminConsole, /path: '\/free-create'/)
  assert.match(freeCreate, /adminAPI\.productionDetail\(generationId\)/)
  assert.match(freeCreate, /loadStandaloneProductionReproduction/)
  assert.match(freeCreate, /当前提示词、参数和素材来自失败时快照/)
  assert.match(freeCreate, /const canCreate = computed\(\(\) => !reproductionMode\.value/)
  assert.match(freeCreate, /function scheduleSave\(\) \{ if \(loadingShot\.value \|\| reproductionMode\.value/)
  assert.match(freeCreate, /function flushPromptBeforePageHide\(\) \{ if \(reproductionMode\.value\) return/)
  assert.match(freeCreate, /document\.execCommand\('copy'\)/)
  assert.match(freeCreate, /delete query\.replay_generation_id/)
})

test('project shot reorder keeps generated media and completed presentation', () => {
  assert.match(freeCreate, /video_url: local\.video_url \|\| remote\.video_url/)
  assert.match(freeCreate, /poster_local_path: local\.poster_local_path \|\| remote\.poster_local_path/)
  assert.match(freeCreate, /videoUrl && \['pending', 'draft'/)
})

test('embedded storyboard confines wheel scrolling to its side panels', () => {
  assert.match(freeCreate, /\.project-storyboard-page \.shot-list\{flex:1 1 auto;min-height:0\}/)
  assert.match(freeCreate, /@media\(min-width:761px\)\{\.center-stage\{min-height:0;overflow:hidden\}\.shot-script\{flex:1 1 auto;min-height:0;overflow-y:auto;overscroll-behavior-y:contain\}/)
assert.match(freeCreate, /function containWorkbenchScroll\(event\)/)
assert.match(freeCreate, /if \(!panel \|\| panel\.scrollHeight <= panel\.clientHeight\) \{\s*event\.preventDefault\(\)/)
assert.match(freeCreate, /Desktop free-create uses a fixed-height workbench too/)
assert.match(freeCreate, /\.shot-panel\{overflow:hidden\}\.shot-list\{flex:1 1 auto;min-height:0\}/)
  assert.match(freeCreate, /\.omni-page\.embedded\.project-storyboard-page\{position:sticky!important;top:58px;z-index:20;height:calc\(100dvh - 58px\)!important/)
  assert.match(filmCreate, /\.storyboard-stage-active \.omni-page\.embedded\.project-storyboard-page\{position:static!important;top:auto;height:auto!important;min-height:0!important;overflow:hidden!important;flex:1/)
})

test('long prompt text keeps an independently scrollable textarea', () => {
  const promptEditor = readFileSync(new URL('../src/components/OmniAssetPromptEditor.vue', import.meta.url), 'utf8')
  assert.match(freeCreate, /const promptEditor = event\.target\.closest\('textarea\.el-textarea__inner, \.prompt-rich-editor'\)/)
  assert.match(freeCreate, /promptEditor\.scrollHeight <= promptEditor\.clientHeight/)
  assert.match(freeCreate, /event\.target\.closest\('\.shot-list, \.creation-panel, \.shot-script,/)
  assert.match(promptEditor, /overflow-y: auto; overscroll-behavior-y: contain; scrollbar-gutter: stable/)
})

test('project settings communicate first-shot master, inherited and override states', () => {
  assert.match(freeCreate, /首镜母版/)
  assert.match(freeCreate, /跟随首镜/)
  assert.match(freeCreate, /当前镜头覆盖/)
  assert.match(freeCreate, /updateGenerationSettings/)
})

test('asset mention menus are teleported translucent overlays with bounded internal scrolling', () => {
  for (const source of [promptEditor, universalEditor]) {
    assert.match(source, /teleport to="body"/i)
    assert.match(source, /backdrop-filter:\s*blur/i)
    assert.match(source, /260/)
  }
  assert.match(promptEditor, /pickerMatches\.value\.slice\(0, 30\)/)
  assert.match(promptEditor, /pickerMatchCount > pickerAssets\.length/)
  assert.match(promptEditor, /loading="lazy" decoding="async"/)
  assert.match(promptEditor, /const caretRect = visualRectForCollapsedRange\(range\)/)
  assert.match(promptEditor, /window\.addEventListener\('scroll', schedulePickerPosition, true\)/)
  assert.match(promptEditor, /transform: placeBelow \? 'none' : 'translateY\(-100%\)'/)
  assert.match(promptEditor, /if \(anchor\.bottom < visibleTop \|\| anchor\.top > visibleBottom\)/)
  assert.doesNotMatch(promptEditor, /const top = rect\.top >= height \+ 12/)
})

test('asset drag shows an exact text-boundary caret and rejects whitespace-only lines', () => {
  assert.match(dragPreview, /setDragImage\(transparentPreview, 0, 0\)/)
  assert.match(freeCreate, /@pointerdown="!reproductionMode && beginAssetPointerDrag\(\$event, promptAssetFor\(asset\)\)"/)
  assert.match(pointerDrag, /Math\.hypot\([\s\S]*< 6/)
  assert.match(pointerDrag, /ASSET_POINTER_MOVE/)
  assert.match(pointerDrag, /ASSET_POINTER_DROP/)
  assert.match(pointerDrag, /event\.preventDefault\(\)/)
  assert.match(pointerDrag, /setPointerCapture/)
  assert.match(promptEditor, /window\.addEventListener\(ASSET_POINTER_MOVE/)
  assert.match(promptEditor, /insertAsset\(detail\.asset, \{ offset: point\.offset \}\)/)
  assert.match(filmCreate, /setTransparentDragPreview\(e\)/)
  assert.match(promptEditor, /caretRect = visualRectForCollapsedRange\(range\)/)
  assert.match(promptEditor, /function visualRectForCollapsedRange\(range\)/)
  assert.match(promptEditor, /function offsetForRange\(range\)/)
  assert.match(promptEditor, /document\.caretPositionFromPoint/)
  assert.match(promptEditor, /不要改写原生 Selection/)
  assert.match(promptEditor, /const rect = editorRef\.value\?\.getBoundingClientRect\(\)/)
  assert.match(promptEditor, /释放位置才是最终意图/)
  assert.match(promptEditor, /node\.nodeType === Node\.TEXT_NODE/)
  assert.match(promptEditor, /prevRect\.right/)
  assert.match(promptEditor, /source\.slice\(lineStart, lineEnd\)\.trim\(\)/)
  assert.match(promptEditor, /rejected: true/)
  assert.match(promptEditor, /point && !point\.rejected/)
  assert.match(promptEditor, /source\[i\] === '\\n'/)
  assert.match(universalEditor, /blankLineDropMeta/)
  assert.match(universalEditor, /omni-drop-indicator/)
  assert.doesNotMatch(promptEditor, /class="mention-anchor"/)
  assert.doesNotMatch(promptEditor, /el-tag v-for="asset in referenced"/)
})

test('在长提示词中插入素材只重绘一次并保持编辑器滚动位置', () => {
  assert.match(promptEditor, /const scrollPosition = \{ top: editorRef\.value\?\.scrollTop \|\| 0/)
  assert.match(promptEditor, /nextTick\(\(\) => restoreEditorAfterInsert\(caret, scrollPosition\)\)/)
  assert.match(promptEditor, /function focusEditorAtOffset\(offset, scrollPosition\)/)
  assert.match(promptEditor, /el\.focus\(\{ preventScroll: true \}\)/)
  assert.match(promptEditor, /el\.scrollTop = scrollPosition\?\.top \|\| 0/)
})

test('@ 素材筛选随光标位置立即更新', () => {
  assert.match(promptEditor, /const lastCaretOffset = ref\(0\)/)
  assert.match(promptEditor, /const cursor = lastCaretOffset\.value/)
  assert.match(promptEditor, /lastCaretOffset\.value = caretOffset\(\)/)
})

test('billing adjustment explanation is explicitly optional', () => {
  const admin = readFileSync(new URL('../src/views/AdminConsole.vue', import.meta.url), 'utf8')
  assert.match(admin, /情况说明（选填）/)
  assert.doesNotMatch(admin, /请填写调整说明/)
})
